'use client';

import { useEffect, useMemo, useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';
import { Package, Plus, X, Search, ExternalLink } from '@/components/icons';
import { Badge } from '@/components/ui';

type Shipment={id:string;status:string;carrier:string|null;tracking_code:string|null;shipped_at:string|null;delivered_at:string|null;created_at:string;campaigns?:{name:string;clients?:{name:string}|null}|null;influencers?:{full_name:string}|null;products?:{name:string;sku:string|null;variant:string|null;color:string|null}|null};
type Campaign={id:string;name:string;client_id:string;clients?:{name:string}|null};type Participant={campaign_id:string;influencer_id:string;influencers?:{full_name:string}|null};
const statusLabels:Record<string,string>={to_prepare:'A preparar',ready:'Pronto',shipped:'Enviado',in_transit:'Em trânsito',delivered:'Entregue',cancelled:'Cancelado'};
const tone=(s:string)=>s==='delivered'?'green':s==='shipped'||s==='in_transit'?'blue':s==='ready'?'violet':s==='cancelled'?'red':'amber';

export default function Logistica(){
  const supabase=useMemo(()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;return u&&k?createBrowserClient(u,k):null},[]);
  const [items,setItems]=useState<Shipment[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [participants,setParticipants]=useState<Participant[]>([]);const [orgId,setOrgId]=useState('');const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [form,setForm]=useState({campaign_id:'',influencer_id:'',product_name:'',sku:'',variant:'',color:'',carrier:'',tracking_code:''});
  async function load(){if(!supabase){setLoading(false);return}setLoading(true);setError('');const {data:m}=await supabase.from('organization_members').select('organization_id').limit(1).maybeSingle();if(!m){setError('Usuário sem workspace.');setLoading(false);return}setOrgId(m.organization_id);const [sQ,cQ,pQ]=await Promise.all([supabase.from('shipments').select('id,status,carrier,tracking_code,shipped_at,delivered_at,created_at,campaigns(name,clients(name)),influencers(full_name),products(name,sku,variant,color)').order('created_at',{ascending:false}),supabase.from('campaigns').select('id,name,client_id,clients(name)').neq('status','completed').order('created_at',{ascending:false}),supabase.from('campaign_influencers').select('campaign_id,influencer_id,influencers(full_name)').neq('casting_stage','rejected')]);if(sQ.error)setError(sQ.error.message);setItems((sQ.data||[]) as unknown as Shipment[]);setCampaigns((cQ.data||[]) as unknown as Campaign[]);setParticipants((pQ.data||[]) as unknown as Participant[]);setLoading(false)}
  useEffect(()=>{load()},[supabase]);
  async function createShipment(e:React.FormEvent){e.preventDefault();if(!supabase||!orgId||!form.campaign_id||!form.influencer_id||!form.product_name.trim())return;setSaving(true);setError('');const campaign=campaigns.find(c=>c.id===form.campaign_id);const {data:product,error:pe}=await supabase.from('products').insert({organization_id:orgId,campaign_id:form.campaign_id,client_id:campaign?.client_id||null,name:form.product_name.trim(),sku:form.sku.trim()||null,variant:form.variant.trim()||null,color:form.color.trim()||null}).select('id').single();if(pe||!product){setSaving(false);setError(pe?.message||'Falha ao criar produto.');return}const {error:se}=await supabase.from('shipments').insert({organization_id:orgId,campaign_id:form.campaign_id,influencer_id:form.influencer_id,product_id:product.id,status:form.tracking_code?'shipped':'to_prepare',carrier:form.carrier.trim()||null,tracking_code:form.tracking_code.trim()||null,shipped_at:form.tracking_code?new Date().toISOString():null});setSaving(false);if(se){setError(se.message);return}setOpen(false);setForm({campaign_id:'',influencer_id:'',product_name:'',sku:'',variant:'',color:'',carrier:'',tracking_code:''});await load()}
  async function changeStatus(id:string,status:string){if(!supabase)return;const patch:Record<string,unknown>={status,updated_at:new Date().toISOString()};if(status==='shipped')patch.shipped_at=new Date().toISOString();if(status==='delivered')patch.delivered_at=new Date().toISOString();await supabase.from('shipments').update(patch).eq('id',id);await load()}
  const filtered=items.filter(s=>`${s.influencers?.full_name||''} ${s.products?.name||''} ${s.campaigns?.name||''} ${s.tracking_code||''}`.toLowerCase().includes(query.toLowerCase()));const available=participants.filter(p=>!form.campaign_id||p.campaign_id===form.campaign_id);const counts={prepare:items.filter(i=>i.status==='to_prepare').length,transit:items.filter(i=>['shipped','in_transit'].includes(i.status)).length,delivered:items.filter(i=>i.status==='delivered').length};
  return <>
    <div className="page-head"><div><div className="eyebrow">Produtos & envios</div><h1 className="page-title">Logística</h1><p className="page-subtitle">Produtos, creators, rastreio e entrega ligados à campanha correta.</p></div><button className="primary-btn keep-text" onClick={()=>setOpen(v=>!v)}>{open?<X size={16}/>:<Plus size={16}/>} {open?'Fechar':'Novo envio'}</button></div>
    <div className="grid-metrics"><div className="metric-card"><div className="metric-top"><span>A preparar</span><Package size={15}/></div><div className="metric-value">{counts.prepare}</div><div className="metric-meta">produtos aguardando expedição</div></div><div className="metric-card"><div className="metric-top"><span>Em trânsito</span><Package size={15}/></div><div className="metric-value">{counts.transit}</div><div className="metric-meta">envios em andamento</div></div><div className="metric-card metric-card-accent"><div className="metric-top"><span>Entregues</span><Package size={15}/></div><div className="metric-value">{counts.delivered}</div><div className="metric-meta">entregas concluídas</div></div></div>
    {open&&<form className="form-card" onSubmit={createShipment} style={{marginBottom:16}}><div className="form-section" style={{marginBottom:0,paddingBottom:0,borderBottom:0}}><h3>Novo envio</h3><p>Cria o produto e o registro logístico em uma única ação.</p><div className="form-grid three"><div className="field"><label>Campanha *</label><select required value={form.campaign_id} onChange={e=>setForm({...form,campaign_id:e.target.value,influencer_id:''})}><option value="">Selecione</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.clients?.name} · {c.name}</option>)}</select></div><div className="field"><label>Creator *</label><select required value={form.influencer_id} onChange={e=>setForm({...form,influencer_id:e.target.value})}><option value="">Selecione</option>{available.map(p=><option key={`${p.campaign_id}-${p.influencer_id}`} value={p.influencer_id}>{p.influencers?.full_name||'Creator'}</option>)}</select></div><div className="field"><label>Produto *</label><input required value={form.product_name} onChange={e=>setForm({...form,product_name:e.target.value})} placeholder="Ex.: Knu Skool"/></div><div className="field"><label>SKU</label><input value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></div><div className="field"><label>Variação / tamanho</label><input value={form.variant} onChange={e=>setForm({...form,variant:e.target.value})}/></div><div className="field"><label>Cor</label><input value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></div><div className="field"><label>Transportadora</label><input value={form.carrier} onChange={e=>setForm({...form,carrier:e.target.value})}/></div><div className="field"><label>Rastreio</label><input value={form.tracking_code} onChange={e=>setForm({...form,tracking_code:e.target.value})}/></div></div><div className="submit-row"><span className="privacy-note">Se houver código de rastreio, o envio já inicia como “Enviado”.</span><button className="primary-btn keep-text" disabled={saving}>{saving?'Salvando…':'Criar envio'}</button></div></div></form>}
    <div className="toolbar"><div className="search-box"><Search size={16}/><input placeholder="Creator, produto, campanha ou rastreio..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div>{error&&<div className="success-box" style={{background:'#fff0f2',color:'#ba3b4d',marginBottom:14}}>{error}</div>}
    <div className="panel table-wrap"><table className="data-table"><thead><tr><th>Creator</th><th>Produto</th><th>Cliente / campanha</th><th>Status</th><th>Transportadora</th><th>Rastreio</th><th>Datas</th></tr></thead><tbody>{loading?<tr><td colSpan={7}>Carregando logística…</td></tr>:filtered.length===0?<tr><td colSpan={7}>Nenhum envio registrado.</td></tr>:filtered.map(s=><tr key={s.id}><td><strong>{s.influencers?.full_name||'—'}</strong></td><td><div className="name-cell"><strong>{s.products?.name||'—'}</strong><span>{[s.products?.variant,s.products?.color,s.products?.sku].filter(Boolean).join(' · ')||'sem variação'}</span></div></td><td><div className="name-cell"><strong>{s.campaigns?.clients?.name||'—'}</strong><span>{s.campaigns?.name||'—'}</span></div></td><td><select value={s.status} onChange={e=>changeStatus(s.id,e.target.value)} style={{border:'1px solid #e1e3eb',borderRadius:9,padding:'7px 8px',background:'#fff'}}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div style={{marginTop:5}}><Badge tone={tone(s.status) as any}>{statusLabels[s.status]||s.status}</Badge></div></td><td>{s.carrier||'—'}</td><td>{s.tracking_code?<span>{s.tracking_code} <ExternalLink size={11}/></span>:'—'}</td><td><div className="name-cell"><strong>{s.shipped_at?`Env. ${new Date(s.shipped_at).toLocaleDateString('pt-BR')}`:'Não enviado'}</strong><span>{s.delivered_at?`Entregue ${new Date(s.delivered_at).toLocaleDateString('pt-BR')}`:''}</span></div></td></tr>)}</tbody></table></div>
  </>;
}
