'use client';

import { useEffect, useMemo, useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';
import { MessageSquareText, Plus, X, Search, ExternalLink } from '@/components/icons';
import { Badge } from '@/components/ui';

type Deliverable={id:string;type:string;quantity:number;status:string;script_due_at:string|null;content_due_at:string|null;publication_due_at:string|null;published_url:string|null;published_at:string|null;campaigns?:{name:string;clients?:{name:string}|null}|null;influencers?:{full_name:string}|null};
type Campaign={id:string;name:string;clients?:{name:string}|null};type Participant={campaign_id:string;influencer_id:string;influencers?:{full_name:string}|null};
const statusLabels:Record<string,string>={not_started:'Não iniciado',waiting_script:'Aguardando roteiro',script_received:'Roteiro recebido',internal_review:'Revisão interna',sent_to_client:'Enviado ao cliente',adjustments:'Ajustes',approved:'Aprovado',waiting_publish:'Aguardando publicação',published:'Publicado',complete:'Concluído'};
const tone=(s:string)=>s==='published'||s==='complete'?'green':s==='approved'||s==='waiting_publish'?'blue':s==='adjustments'?'amber':s==='internal_review'?'violet':'slate';

export default function Conteudos(){
  const supabase=useMemo(()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;return u&&k?createBrowserClient(u,k):null},[]);
  const [items,setItems]=useState<Deliverable[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [participants,setParticipants]=useState<Participant[]>([]);const [orgId,setOrgId]=useState('');const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [form,setForm]=useState({campaign_id:'',influencer_id:'',type:'Reel',quantity:'1',script_due_at:'',content_due_at:'',publication_due_at:''});
  async function load(){if(!supabase){setLoading(false);return}setLoading(true);setError('');const {data:m}=await supabase.from('organization_members').select('organization_id').limit(1).maybeSingle();if(!m){setError('Usuário sem workspace.');setLoading(false);return}setOrgId(m.organization_id);const [dQ,cQ,pQ]=await Promise.all([supabase.from('deliverables').select('id,type,quantity,status,script_due_at,content_due_at,publication_due_at,published_url,published_at,campaigns(name,clients(name)),influencers(full_name)').order('created_at',{ascending:false}),supabase.from('campaigns').select('id,name,clients(name)').neq('status','completed').order('created_at',{ascending:false}),supabase.from('campaign_influencers').select('campaign_id,influencer_id,influencers(full_name)').neq('casting_stage','rejected')]);if(dQ.error)setError(dQ.error.message);setItems((dQ.data||[]) as unknown as Deliverable[]);setCampaigns((cQ.data||[]) as unknown as Campaign[]);setParticipants((pQ.data||[]) as unknown as Participant[]);setLoading(false)}
  useEffect(()=>{load()},[supabase]);
  async function createDeliverable(e:React.FormEvent){e.preventDefault();if(!supabase||!orgId||!form.campaign_id||!form.influencer_id)return;setSaving(true);setError('');const {error:e2}=await supabase.from('deliverables').insert({organization_id:orgId,campaign_id:form.campaign_id,influencer_id:form.influencer_id,type:form.type.trim(),quantity:Number(form.quantity)||1,status:'not_started',script_due_at:form.script_due_at?new Date(form.script_due_at).toISOString():null,content_due_at:form.content_due_at?new Date(form.content_due_at).toISOString():null,publication_due_at:form.publication_due_at?new Date(form.publication_due_at).toISOString():null});setSaving(false);if(e2){setError(e2.message);return}setOpen(false);setForm({campaign_id:'',influencer_id:'',type:'Reel',quantity:'1',script_due_at:'',content_due_at:'',publication_due_at:''});await load()}
  async function changeStatus(id:string,status:string){if(!supabase)return;const patch:Record<string,unknown>={status,updated_at:new Date().toISOString()};if(status==='published'||status==='complete')patch.published_at=new Date().toISOString();await supabase.from('deliverables').update(patch).eq('id',id);await load()}
  async function setPublishedUrl(id:string,current:string|null){if(!supabase)return;const url=window.prompt('Cole a URL da publicação:',current||'');if(url===null)return;await supabase.from('deliverables').update({published_url:url.trim()||null,updated_at:new Date().toISOString()}).eq('id',id);await load()}
  const filtered=items.filter(d=>`${d.type} ${d.influencers?.full_name||''} ${d.campaigns?.name||''}`.toLowerCase().includes(query.toLowerCase()));const available=participants.filter(p=>!form.campaign_id||p.campaign_id===form.campaign_id);const counts={review:items.filter(i=>['script_received','internal_review'].includes(i.status)).length,client:items.filter(i=>['sent_to_client','adjustments'].includes(i.status)).length,approved:items.filter(i=>['approved','waiting_publish'].includes(i.status)).length,published:items.filter(i=>['published','complete'].includes(i.status)).length};
  return <>
    <div className="page-head"><div><div className="eyebrow">Entregáveis & aprovações</div><h1 className="page-title">Conteúdos</h1><p className="page-subtitle">Roteiro, revisão, cliente, ajustes, aprovação e publicação em uma única fila.</p></div><button className="primary-btn keep-text" onClick={()=>setOpen(v=>!v)}>{open?<X size={16}/>:<Plus size={16}/>} {open?'Fechar':'Novo entregável'}</button></div>
    <div className="grid-metrics"><div className="metric-card"><div className="metric-top"><span>Revisão interna</span><MessageSquareText size={15}/></div><div className="metric-value">{counts.review}</div><div className="metric-meta">roteiros/conteúdos para revisar</div></div><div className="metric-card"><div className="metric-top"><span>Com cliente</span><MessageSquareText size={15}/></div><div className="metric-value">{counts.client}</div><div className="metric-meta">aprovação ou ajustes</div></div><div className="metric-card"><div className="metric-top"><span>Aprovados</span><MessageSquareText size={15}/></div><div className="metric-value">{counts.approved}</div><div className="metric-meta">aguardando publicação</div></div><div className="metric-card metric-card-accent"><div className="metric-top"><span>Publicados</span><MessageSquareText size={15}/></div><div className="metric-value">{counts.published}</div><div className="metric-meta">entregas finalizadas</div></div></div>
    {open&&<form className="form-card" onSubmit={createDeliverable} style={{marginBottom:16}}><div className="form-section" style={{marginBottom:0,paddingBottom:0,borderBottom:0}}><h3>Novo entregável</h3><p>Vincule diretamente ao creator e à campanha.</p><div className="form-grid three"><div className="field"><label>Campanha *</label><select required value={form.campaign_id} onChange={e=>setForm({...form,campaign_id:e.target.value,influencer_id:''})}><option value="">Selecione</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.clients?.name} · {c.name}</option>)}</select></div><div className="field"><label>Creator *</label><select required value={form.influencer_id} onChange={e=>setForm({...form,influencer_id:e.target.value})}><option value="">Selecione</option>{available.map(p=><option key={`${p.campaign_id}-${p.influencer_id}`} value={p.influencer_id}>{p.influencers?.full_name||'Creator'}</option>)}</select></div><div className="field"><label>Tipo</label><input value={form.type} onChange={e=>setForm({...form,type:e.target.value})} placeholder="Reel, Story, TikTok..."/></div><div className="field"><label>Quantidade</label><input type="number" min="1" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></div><div className="field"><label>Prazo roteiro</label><input type="datetime-local" value={form.script_due_at} onChange={e=>setForm({...form,script_due_at:e.target.value})}/></div><div className="field"><label>Prazo conteúdo</label><input type="datetime-local" value={form.content_due_at} onChange={e=>setForm({...form,content_due_at:e.target.value})}/></div><div className="field"><label>Prazo publicação</label><input type="datetime-local" value={form.publication_due_at} onChange={e=>setForm({...form,publication_due_at:e.target.value})}/></div></div><div className="submit-row"><span className="privacy-note">Status inicial: Não iniciado.</span><button className="primary-btn keep-text" disabled={saving}>{saving?'Salvando…':'Criar entregável'}</button></div></div></form>}
    <div className="toolbar"><div className="search-box"><Search size={16}/><input placeholder="Creator, campanha ou formato..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div>{error&&<div className="success-box" style={{background:'#fff0f2',color:'#ba3b4d',marginBottom:14}}>{error}</div>}
    <div className="panel table-wrap"><table className="data-table"><thead><tr><th>Creator</th><th>Cliente / campanha</th><th>Entrega</th><th>Status</th><th>Prazos</th><th>Publicação</th></tr></thead><tbody>{loading?<tr><td colSpan={6}>Carregando conteúdos…</td></tr>:filtered.length===0?<tr><td colSpan={6}>Nenhum entregável registrado.</td></tr>:filtered.map(d=><tr key={d.id}><td><strong>{d.influencers?.full_name||'—'}</strong></td><td><div className="name-cell"><strong>{d.campaigns?.clients?.name||'—'}</strong><span>{d.campaigns?.name||'—'}</span></div></td><td>{d.quantity}× {d.type}</td><td><select value={d.status} onChange={e=>changeStatus(d.id,e.target.value)} style={{border:'1px solid #e1e3eb',borderRadius:9,padding:'7px 8px',background:'#fff'}}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div style={{marginTop:5}}><Badge tone={tone(d.status) as any}>{statusLabels[d.status]||d.status}</Badge></div></td><td><div className="name-cell"><strong>{d.content_due_at?`Conteúdo ${new Date(d.content_due_at).toLocaleDateString('pt-BR')}`:'Sem prazo conteúdo'}</strong><span>{d.publication_due_at?`Publicação ${new Date(d.publication_due_at).toLocaleDateString('pt-BR')}`:''}</span></div></td><td>{d.published_url?<a href={d.published_url} target="_blank" rel="noreferrer" className="ghost-btn">Abrir <ExternalLink size={12}/></a>:<button className="ghost-btn" onClick={()=>setPublishedUrl(d.id,d.published_url)}>Adicionar URL</button>}</td></tr>)}</tbody></table></div>
  </>;
}
