'use client';

import { useEffect, useMemo, useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';
import { Badge } from '@/components/ui';
import { Search, Plus, MoreHorizontal, FileCheck2, Clock3, ExternalLink, X } from '@/components/icons';

type Contract={id:string;status:string;agreed_fee:number|null;missing_fields:string[]|null;external_document_url:string|null;created_at:string;updated_at:string;influencers?:{full_name:string}|null;clients?:{name:string}|null;campaigns?:{name:string}|null};
type Influencer={id:string;full_name:string}; type Client={id:string;name:string}; type Campaign={id:string;name:string;client_id:string};
const labels:Record<string,string>={needed:'Preparar contrato',preparing:'Em preparação',review:'Em revisão',sent:'Enviado',awaiting_signature:'Aguardando assinatura',signed:'Assinado',complete:'Concluído'};
const tone=(s:string)=>s==='signed'||s==='complete'?'green':s==='awaiting_signature'||s==='sent'?'blue':s==='needed'||s==='preparing'?'amber':'slate';

export default function Contratos(){
  const supabase=useMemo(()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;return u&&k?createBrowserClient(u,k):null},[]);
  const [items,setItems]=useState<Contract[]>([]);const [influencers,setInfluencers]=useState<Influencer[]>([]);const [clients,setClients]=useState<Client[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [orgId,setOrgId]=useState('');const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);
  const [form,setForm]=useState({influencer_id:'',client_id:'',campaign_id:'',agreed_fee:'',missing_fields:''});
  async function load(){if(!supabase){setLoading(false);return}setLoading(true);const {data:m}=await supabase.from('organization_members').select('organization_id').limit(1).maybeSingle();if(!m){setError('Usuário sem workspace.');setLoading(false);return}setOrgId(m.organization_id);const [{data:c,error:e},{data:i},{data:cl},{data:cp}]=await Promise.all([supabase.from('contracts').select('id,status,agreed_fee,missing_fields,external_document_url,created_at,updated_at,influencers(full_name),clients(name),campaigns(name)').order('updated_at',{ascending:false}),supabase.from('influencers').select('id,full_name').order('full_name'),supabase.from('clients').select('id,name').eq('status','active').order('name'),supabase.from('campaigns').select('id,name,client_id').order('created_at',{ascending:false})]);if(e)setError(e.message);else setItems((c||[]) as unknown as Contract[]);setInfluencers((i||[]) as Influencer[]);setClients((cl||[]) as Client[]);setCampaigns((cp||[]) as Campaign[]);setLoading(false)}
  useEffect(()=>{load()},[supabase]);
  async function createContract(e:React.FormEvent){e.preventDefault();if(!supabase||!orgId)return;setSaving(true);setError('');const {data:{user}}=await supabase.auth.getUser();const missing=form.missing_fields.split(',').map(v=>v.trim()).filter(Boolean);const {error:e2}=await supabase.from('contracts').insert({organization_id:orgId,influencer_id:form.influencer_id,client_id:form.client_id||null,campaign_id:form.campaign_id||null,agreed_fee:form.agreed_fee?Number(form.agreed_fee):null,missing_fields:missing,status:'needed',owner_user_id:user?.id||null});setSaving(false);if(e2){setError(e2.message);return}setOpen(false);setForm({influencer_id:'',client_id:'',campaign_id:'',agreed_fee:'',missing_fields:''});await load()}
  async function changeStatus(id:string,status:string){if(!supabase)return;const patch:any={status,updated_at:new Date().toISOString()};if(status==='sent')patch.sent_at=new Date().toISOString();if(status==='signed')patch.signed_at=new Date().toISOString();await supabase.from('contracts').update(patch).eq('id',id);await load()}
  const filtered=items.filter(c=>`${c.influencers?.full_name||''} ${c.clients?.name||''} ${c.campaigns?.name||''}`.toLowerCase().includes(query.toLowerCase()));
  const counts={needed:items.filter(c=>['needed','preparing'].includes(c.status)).length,review:items.filter(c=>c.status==='review').length,signature:items.filter(c=>c.status==='awaiting_signature').length,signed:items.filter(c=>['signed','complete'].includes(c.status)).length};
  return <>
    <div className="page-head"><div><div className="eyebrow">Controle manual assistido</div><h1 className="page-title">Contratos</h1><p className="page-subtitle">O sistema organiza dados e etapas; preparação e revisão continuam sob responsabilidade humana.</p></div><button className="primary-btn keep-text" onClick={()=>setOpen(v=>!v)}>{open?<X size={16}/>:<Plus size={16}/>} {open?'Fechar':'Novo registro'}</button></div>
    {open&&<form className="form-card" onSubmit={createContract} style={{marginBottom:16}}><div className="form-section" style={{marginBottom:0,paddingBottom:0,borderBottom:0}}><h3>Novo contrato</h3><p>Cria o registro operacional; não gera nem envia documento automaticamente.</p><div className="form-grid three"><div className="field"><label>Influencer *</label><select required value={form.influencer_id} onChange={e=>setForm({...form,influencer_id:e.target.value})}><option value="">Selecione</option>{influencers.map(i=><option value={i.id} key={i.id}>{i.full_name}</option>)}</select></div><div className="field"><label>Cliente</label><select value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value,campaign_id:''})}><option value="">Nenhum</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Campanha</label><select value={form.campaign_id} onChange={e=>setForm({...form,campaign_id:e.target.value})}><option value="">Nenhuma</option>{campaigns.filter(c=>!form.client_id||c.client_id===form.client_id).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Valor acordado</label><input type="number" min="0" step="0.01" value={form.agreed_fee} onChange={e=>setForm({...form,agreed_fee:e.target.value})}/></div><div className="field" style={{gridColumn:'span 2'}}><label>Dados faltantes</label><input value={form.missing_fields} onChange={e=>setForm({...form,missing_fields:e.target.value})} placeholder="Ex.: CNPJ, e-mail, endereço (separe por vírgula)"/></div></div><div className="submit-row"><span className="privacy-note">Status inicial: Preparar contrato.</span><button className="primary-btn" disabled={saving}>{saving?'Salvando…':'Criar registro'}</button></div></div></form>}
    <div className="grid-metrics"><div className="metric-card"><div className="metric-top"><span>Para preparar</span><FileCheck2 size={15}/></div><div className="metric-value">{counts.needed}</div><div className="metric-meta">fila de preparação</div></div><div className="metric-card"><div className="metric-top"><span>Em revisão</span><Clock3 size={15}/></div><div className="metric-value">{counts.review}</div><div className="metric-meta">checagem interna</div></div><div className="metric-card"><div className="metric-top"><span>Aguardando assinatura</span><Clock3 size={15}/></div><div className="metric-value">{counts.signature}</div><div className="metric-meta">follow-up pendente</div></div><div className="metric-card metric-card-accent"><div className="metric-top"><span>Assinados</span><FileCheck2 size={15}/></div><div className="metric-value">{counts.signed}</div><div className="metric-meta">registros concluídos/assinados</div></div></div>
    <div className="toolbar"><div className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Creator, cliente ou campanha..."/></div></div>
    {error&&<div className="success-box" style={{background:'#fff0f2',color:'#ba3b4d',marginBottom:14}}>{error}</div>}
    <div className="panel table-wrap"><table className="data-table"><thead><tr><th>Influencer</th><th>Cliente / campanha</th><th>Status</th><th>Dados faltantes</th><th>Valor</th><th>Atualização</th><th>Documento</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={8}>Carregando contratos…</td></tr>:filtered.length===0?<tr><td colSpan={8}>Nenhum contrato cadastrado.</td></tr>:filtered.map(c=><tr key={c.id}><td><strong>{c.influencers?.full_name||'Influencer'}</strong></td><td><div className="name-cell"><strong>{c.clients?.name||'—'}</strong><span>{c.campaigns?.name||'—'}</span></div></td><td><select value={c.status} onChange={e=>changeStatus(c.id,e.target.value)} style={{border:'1px solid #e1e3eb',borderRadius:9,padding:'7px 8px',background:'#fff'}}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></td><td>{!c.missing_fields||c.missing_fields.length===0?<Badge tone="green">Completo</Badge>:<Badge tone="red">{c.missing_fields.join(', ')}</Badge>}</td><td>{c.agreed_fee!=null?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c.agreed_fee):'—'}</td><td>{new Date(c.updated_at).toLocaleDateString('pt-BR')}</td><td>{c.external_document_url?<a className="ghost-btn" href={c.external_document_url} target="_blank" rel="noreferrer">Abrir <ExternalLink size={12}/></a>:'—'}</td><td><MoreHorizontal size={16}/></td></tr>)}</tbody></table></div>
  </>;
}
