'use client';
import { FormEvent, useState } from 'react';
import { CheckCircle2, ShieldCheck } from '@/components/icons';
import BrandLogo from '@/components/brand-logo';

export default function InfluencerForm(){
  const [sent,setSent]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');const form=new FormData(e.currentTarget);const payload=Object.fromEntries(form.entries());try{const r=await fetch('/api/intake',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('Falha ao enviar');setSent(true)}catch{setError('Não foi possível enviar agora. Confira os dados e tente novamente.')}finally{setLoading(false)}}
  if(sent)return <div className="success-screen"><div className="success-icon"><CheckCircle2 size={26}/></div><h2>Cadastro recebido</h2><p>Suas informações foram enviadas para a equipe. Elas entram na base como um novo cadastro para revisão interna antes de qualquer próxima etapa.</p></div>;
  return <div className="public-wrap">
    <div className="public-brand"><BrandLogo size={42} priority/><div><strong>Cadastro de Influencer</strong><span>Agency Operations</span></div></div>
    <div className="public-hero"><div className="eyebrow" style={{color:'#aeb3bb'}}>Cadastro seguro</div><h1>Precisamos conhecer você um pouco melhor.</h1><p>Preencha seus dados com atenção. Eles serão usados pela equipe para cadastro, campanhas, contratos e possíveis envios de produtos. O preenchimento não gera contrato automaticamente.</p></div>
    <form className="form-card" onSubmit={submit}>
      <input name="website" tabIndex={-1} autoComplete="off" style={{position:'absolute',left:'-9999px'}}/>
      <div className="form-section"><h3>Dados pessoais</h3><p>Informações principais para identificação e contato.</p><div className="form-grid"><div className="field"><label>Nome completo *</label><input name="full_name" required/></div><div className="field"><label>Nome artístico</label><input name="stage_name"/></div><div className="field"><label>CPF *</label><input name="cpf" required placeholder="000.000.000-00"/></div><div className="field"><label>Data de nascimento</label><input type="date" name="birth_date"/></div><div className="field"><label>E-mail *</label><input type="email" name="email" required/></div><div className="field"><label>WhatsApp *</label><input name="phone" required placeholder="(11) 99999-9999"/></div></div></div>
      <div className="form-section"><h3>Empresa</h3><p>Se você emite nota fiscal, informe os dados usados em contratação.</p><div className="form-grid"><div className="field"><label>Possui CNPJ?</label><select name="has_company"><option value="yes">Sim</option><option value="no">Não</option></select></div><div className="field"><label>CNPJ</label><input name="cnpj" placeholder="00.000.000/0000-00"/></div><div className="field"><label>Razão social</label><input name="company_name"/></div><div className="field"><label>Nome fantasia</label><input name="trade_name"/></div></div></div>
      <div className="form-section"><h3>Redes e perfil</h3><p>Inclua as redes em que você produz conteúdo.</p><div className="form-grid"><div className="field"><label>Instagram *</label><input name="instagram" required placeholder="@seuusuario"/></div><div className="field"><label>TikTok</label><input name="tiktok"/></div><div className="field"><label>YouTube</label><input name="youtube"/></div><div className="field"><label>Nicho principal</label><input name="niche" placeholder="Moda, lifestyle, beleza..."/></div><div className="field"><label>Seguidores Instagram</label><input type="number" name="instagram_followers"/></div><div className="field"><label>Cidade / Estado</label><input name="city_state"/></div></div></div>
      <div className="form-section"><h3>Endereço para envios</h3><p>Usaremos estes dados caso alguma campanha envolva produto físico.</p><div className="form-grid three"><div className="field"><label>CEP *</label><input name="postal_code" required/></div><div className="field full" style={{gridColumn:'span 2'}}><label>Rua *</label><input name="street" required/></div><div className="field"><label>Número *</label><input name="street_number" required/></div><div className="field"><label>Complemento</label><input name="complement"/></div><div className="field"><label>Bairro *</label><input name="district" required/></div><div className="field"><label>Cidade *</label><input name="city" required/></div><div className="field"><label>Estado *</label><input name="state" required maxLength={2}/></div></div></div>
      <div className="form-section"><h3>Tamanhos</h3><p>Evita precisar solicitar novamente dados básicos quando houver gifting.</p><div className="form-grid three"><div className="field"><label>Calçado</label><input name="shoe_size"/></div><div className="field"><label>Camiseta</label><input name="shirt_size"/></div><div className="field"><label>Calça</label><input name="pants_size"/></div></div></div>
      <div className="form-section"><h3>Observações</h3><div className="field"><label>Há alguma informação importante que a equipe deveria saber?</label><textarea name="notes"/></div></div>
      {error&&<div className="success-box" style={{background:'var(--red-bg)',color:'var(--red)'}}>{error}</div>}
      <div className="submit-row"><div style={{display:'flex',alignItems:'center',gap:8,color:'var(--muted)',fontSize:10}}><ShieldCheck size={15}/> Informações usadas apenas para operação e contratação.</div><button className="primary-btn keep-text" disabled={loading}>{loading?'Enviando...':'Enviar cadastro'}</button></div>
      <div className="privacy-note">Ao enviar, você confirma que os dados informados são verdadeiros e autoriza seu uso para cadastro operacional, avaliação de campanhas, contratos e logística relacionada às ações da agência.</div>
    </form>
  </div>
}
