'use client';

import { useEffect, useMemo, useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';
import { Badge } from '@/components/ui';
import { Search, UploadCloud, ExternalLink, FileText, ImageIcon, FileSpreadsheet, MoreHorizontal, Cloud, X } from '@/components/icons';

type FileRow={id:string;name:string;category:string|null;provider:string;external_url:string|null;mime_type:string|null;created_at:string};
const FileIcon=({mime,name}:{mime:string|null;name:string})=>mime?.includes('spreadsheet')||name.endsWith('.xlsx')||name.endsWith('.csv')?<FileSpreadsheet size={17}/>:mime?.startsWith('image/')||mime?.startsWith('video/')?<ImageIcon size={17}/>:<FileText size={17}/>;

export default function Arquivos(){
  const supabase=useMemo(()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;return u&&k?createBrowserClient(u,k):null},[]);
  const [items,setItems]=useState<FileRow[]>([]);const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [connected,setConnected]=useState(false);const [open,setOpen]=useState(false);const [uploading,setUploading]=useState(false);const [file,setFile]=useState<File|null>(null);const [form,setForm]=useState({client:'',campaign:'',creator:'',category:'Arquivos'});
  async function load(){if(!supabase){setLoading(false);return}setLoading(true);const [{data:f,error:e},{data:i}]=await Promise.all([supabase.from('files').select('id,name,category,provider,external_url,mime_type,created_at').order('created_at',{ascending:false}),supabase.from('integrations').select('status').eq('provider','google_workspace').limit(1).maybeSingle()]);if(e)setError(e.message);else setItems((f||[]) as FileRow[]);setConnected(i?.status==='connected');setLoading(false)}
  useEffect(()=>{load()},[supabase]);
  async function upload(e:React.FormEvent){e.preventDefault();if(!file)return;setUploading(true);setError('');const fd=new FormData();fd.append('file',file);fd.append('client',form.client||'Sem cliente');fd.append('campaign',form.campaign||'Geral');fd.append('creator',form.creator||'Geral');fd.append('category',form.category||'Arquivos');const res=await fetch('/api/google/drive/upload',{method:'POST',body:fd});const body=await res.json().catch(()=>({}));setUploading(false);if(!res.ok){setError(body.error||'Falha no upload');return}setFile(null);setOpen(false);setForm({client:'',campaign:'',creator:'',category:'Arquivos'});await load()}
  const filtered=items.filter(f=>`${f.name} ${f.category||''}`.toLowerCase().includes(query.toLowerCase()));
  return <>
    <div className="page-head"><div><div className="eyebrow">Google Drive como repositório</div><h1 className="page-title">Arquivos</h1><p className="page-subtitle">Uploads reais para a estrutura Cliente → Campanha → Creator → Categoria, com referência salva no Supabase.</p></div><button className="primary-btn keep-text" onClick={()=>setOpen(v=>!v)}>{open?<X size={16}/>:<UploadCloud size={16}/>} {open?'Fechar':'Subir arquivo'}</button></div>
    <div className="panel" style={{marginBottom:16}}><div className="panel-body"><div className="integration-card" style={{border:0,padding:0}}><div className="integration-icon"><Cloud size={21}/></div><div className="integration-info"><strong>Google Drive</strong><span>{connected?'Conta conectada. Os uploads serão enviados para a pasta raiz configurada.':'Conecte o Google Workspace em Configurações → Integrações antes de enviar arquivos.'}</span></div><Badge tone={connected?'green':'amber'}>{connected?'Conectado':'Não conectado'}</Badge></div></div></div>
    {open&&<form className="form-card" onSubmit={upload} style={{marginBottom:16}}><div className="form-section" style={{marginBottom:0,paddingBottom:0,borderBottom:0}}><h3>Enviar para o Drive</h3><p>Informe a estrutura de destino. Pastas inexistentes serão criadas automaticamente.</p><div className="form-grid three"><div className="field"><label>Arquivo *</label><input type="file" required onChange={e=>setFile(e.target.files?.[0]||null)}/></div><div className="field"><label>Cliente</label><input value={form.client} onChange={e=>setForm({...form,client:e.target.value})} placeholder="Ex.: Vans"/></div><div className="field"><label>Campanha</label><input value={form.campaign} onChange={e=>setForm({...form,campaign:e.target.value})} placeholder="Ex.: Knu Skool — Agosto"/></div><div className="field"><label>Creator</label><input value={form.creator} onChange={e=>setForm({...form,creator:e.target.value})} placeholder="Ex.: Ana Silva"/></div><div className="field"><label>Categoria</label><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Arquivos</option><option>Contratos</option><option>Briefings</option><option>Conteúdos</option><option>Métricas</option><option>Financeiro</option></select></div></div><div className="submit-row"><span className="privacy-note">O arquivo continua armazenado no Google Drive; o Arcana salva a referência.</span><button className="primary-btn" disabled={uploading||!connected}>{uploading?'Enviando…':connected?'Enviar arquivo':'Conecte o Drive primeiro'}</button></div></div></form>}
    <div className="toolbar"><div className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar arquivo..."/></div></div>
    {error&&<div className="success-box" style={{background:'#fff0f2',color:'#ba3b4d',marginBottom:14}}>{error}</div>}
    <div className="panel table-wrap"><table className="data-table"><thead><tr><th>Arquivo</th><th>Categoria</th><th>Atualização</th><th>Armazenamento</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={5}>Carregando arquivos…</td></tr>:filtered.length===0?<tr><td colSpan={5}>Nenhum arquivo registrado.</td></tr>:filtered.map(f=><tr key={f.id}><td><div className="person"><div className="task-icon"><FileIcon mime={f.mime_type} name={f.name}/></div><strong>{f.name}</strong></div></td><td><Badge>{f.category||'Arquivo'}</Badge></td><td>{new Date(f.created_at).toLocaleString('pt-BR')}</td><td>{f.external_url?<a className="ghost-btn" href={f.external_url} target="_blank" rel="noreferrer">Drive <ExternalLink size={12}/></a>:f.provider}</td><td><MoreHorizontal size={16}/></td></tr>)}</tbody></table></div>
  </>;
}
