'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';
import { Badge } from '@/components/ui';
import { Search, UploadCloud, ExternalLink, FileText, ImageIcon, FileSpreadsheet, MoreHorizontal, Cloud, X, CheckCircle2 } from '@/components/icons';

type FileRow={id:string;name:string;category:string|null;provider:string;external_url:string|null;mime_type:string|null;created_at:string;clients?:{name:string}|null;campaigns?:{name:string}|null;influencers?:{full_name:string}|null};
type Client={id:string;name:string}; type Campaign={id:string;name:string;client_id:string}; type Influencer={id:string;full_name:string};
const FileIcon=({mime,name}:{mime:string|null;name:string})=>mime?.includes('spreadsheet')||name.toLowerCase().endsWith('.xlsx')||name.toLowerCase().endsWith('.csv')?<FileSpreadsheet size={17}/>:mime?.startsWith('image/')||mime?.startsWith('video/')?<ImageIcon size={17}/>:<FileText size={17}/>;

export default function Arquivos(){
  const supabase=useMemo(()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;return u&&k?createBrowserClient(u,k):null},[]);
  const fileRef=useRef<HTMLInputElement|null>(null);
  const [items,setItems]=useState<FileRow[]>([]);const [clients,setClients]=useState<Client[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [influencers,setInfluencers]=useState<Influencer[]>([]);const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [connected,setConnected]=useState(false);const [open,setOpen]=useState(false);const [uploading,setUploading]=useState(false);const [form,setForm]=useState({client_id:'',campaign_id:'',influencer_id:'',category:'Arquivos'});
  async function load(){if(!supabase){setLoading(false);setError('Supabase não configurado.');return}setLoading(true);const [{data:f,error:e},{data:i},{data:cl},{data:cp},{data:inf}]=await Promise.all([supabase.from('files').select('id,name,category,provider,external_url,mime_type,created_at,clients(name),campaigns(name),influencers(full_name)').order('created_at',{ascending:false}),supabase.from('integrations').select('status').eq('provider','google_workspace').limit(1).maybeSingle(),supabase.from('clients').select('id,name').eq('status','active').order('name'),supabase.from('campaigns').select('id,name,client_id').order('created_at',{ascending:false}),supabase.from('influencers').select('id,full_name').order('full_name')]);if(e)setError(e.message);else setItems((f||[]) as unknown as FileRow[]);setConnected(i?.status==='connected');setClients((cl||[]) as Client[]);setCampaigns((cp||[]) as Campaign[]);setInfluencers((inf||[]) as Influencer[]);setLoading(false)}
  useEffect(()=>{load()},[supabase]);
  async function upload(e:React.FormEvent){e.preventDefault();const file=fileRef.current?.files?.[0];if(!file){setError('Selecione um arquivo.');return}if(!connected){setError('Conecte o Google Drive primeiro.');return}setUploading(true);setError('');setSuccess('');const client=clients.find(c=>c.id===form.client_id);const campaign=campaigns.find(c=>c.id===form.campaign_id);const creator=influencers.find(i=>i.id===form.influencer_id);const fd=new FormData();fd.append('file',file);fd.append('client',client?.name||'Sem cliente');fd.append('campaign',campaign?.name||'Geral');fd.append('creator',creator?.full_name||'Geral');fd.append('category',form.category||'Arquivos');if(form.client_id)fd.append('client_id',form.client_id);if(form.campaign_id)fd.append('campaign_id',form.campaign_id);if(form.influencer_id)fd.append('influencer_id',form.influencer_id);const res=await fetch('/api/google/drive/upload',{method:'POST',body:fd});const body=await res.json().catch(()=>({}));setUploading(false);if(!res.ok){setError(body.error||'Falha no upload');return}if(fileRef.current)fileRef.current.value='';setOpen(false);setForm({client_id:'',campaign_id:'',influencer_id:'',category:'Arquivos'});setSuccess('Arquivo enviado ao Drive e registrado no Arcana.');await load()}
  const filtered=items.filter(f=>`${f.name} ${f.category||''} ${f.clients?.name||''} ${f.campaigns?.name||''} ${f.influencers?.full_name||''}`.toLowerCase().includes(query.toLowerCase()));const campaignOptions=campaigns.filter(c=>!form.client_id||c.client_id===form.client_id);
  return <>
    <div className="page-head"><div><div className="eyebrow">Google Drive como repositório</div><h1 className="page-title">Arquivos</h1><p className="page-subtitle">Uploads reais para Cliente → Campanha → Creator → Categoria, com referência e contexto salvos no Supabase.</p></div><button className="primary-btn keep-text" onClick={()=>setOpen(v=>!v)}>{open?<X size={16}/>:<UploadCloud size={16}/>} {open?'Fechar':'Subir arquivo'}</button></div>
    <div className="panel" style={{marginBottom:16}}><div className="panel-body"><div className="integration-card" style={{border:0,padding:0}}><div className="integration-icon"><Cloud size={21}/></div><div className="integration-info"><strong>Google Drive</strong><span>{connected?'Conta conectada. Os uploads serão enviados para a pasta raiz configurada.':'Conecte o Google Workspace em Configurações → Integrações antes de enviar arquivos.'}</span></div><Badge tone={connected?'green':'amber'}>{connected?'Conectado':'Não conectado'}</Badge></div></div></div>
    {open&&<form className="form-card" onSubmit={upload} style={{marginBottom:16}}><div className="form-section" style={{marginBottom:0,paddingBottom:0,borderBottom:0}}><h3>Enviar para o Drive</h3><p>Escolha o contexto; pastas inexistentes serão criadas automaticamente.</p><div className="form-grid three"><div className="field"><label>Arquivo *</label><input ref={fileRef} type="file" required/></div><div className="field"><label>Cliente</label><select value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value,campaign_id:''})}><option value="">Sem cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Campanha</label><select value={form.campaign_id} onChange={e=>setForm({...form,campaign_id:e.target.value})}><option value="">Geral</option>{campaignOptions.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Creator</label><select value={form.influencer_id} onChange={e=>setForm({...form,influencer_id:e.target.value})}><option value="">Geral</option>{influencers.map(i=><option key={i.id} value={i.id}>{i.full_name}</option>)}</select></div><div className="field"><label>Categoria</label><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Arquivos</option><option>Contratos</option><option>Briefings</option><option>Castings</option><option>Conteúdos</option><option>Métricas</option><option>Financeiro</option></select></div></div><div className="submit-row"><span className="privacy-note">Limite atual por upload: 50 MB.</span><button className="primary-btn keep-text" disabled={uploading||!connected}>{uploading?'Enviando…':connected?'Enviar arquivo':'Conecte o Drive primeiro'}</button></div></div></form>}
    {error&&<div className="success-box" style={{background:'#fff0f2',color:'#ba3b4d',marginBottom:14}}>{error}</div>}{success&&<div className="success-box" style={{marginBottom:14,display:'flex',alignItems:'center',gap:8}}><CheckCircle2 size={15}/>{success}</div>}
    <div className="toolbar"><div className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar arquivo..."/></div></div>
    <div className="panel table-wrap"><table className="data-table"><thead><tr><th>Arquivo</th><th>Categoria</th><th>Cliente / campanha</th><th>Creator</th><th>Atualização</th><th>Drive</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={7}>Carregando arquivos…</td></tr>:filtered.length===0?<tr><td colSpan={7}>Nenhum arquivo registrado.</td></tr>:filtered.map(f=><tr key={f.id}><td><div className="person"><div className="task-icon"><FileIcon mime={f.mime_type} name={f.name}/></div><strong>{f.name}</strong></div></td><td><Badge>{f.category||'Arquivo'}</Badge></td><td><div className="name-cell"><strong>{f.clients?.name||'—'}</strong><span>{f.campaigns?.name||'—'}</span></div></td><td>{f.influencers?.full_name||'—'}</td><td>{new Date(f.created_at).toLocaleString('pt-BR')}</td><td>{f.external_url?<a className="ghost-btn" href={f.external_url} target="_blank" rel="noreferrer">Drive <ExternalLink size={12}/></a>:f.provider}</td><td><MoreHorizontal size={16}/></td></tr>)}</tbody></table></div>
  </>;
}
