import Link from 'next/link';
import { influencers } from '@/lib/demo-data';
import { Badge } from '@/components/ui';
import { FileCheck2, Package, MessageSquareText, WalletCards, History, Copy, ExternalLink } from '@/components/icons';

export default async function InfluencerDetail({params}:{params:Promise<{id:string}>}){const {id}=await params;const i=influencers.find(x=>x.id===id)??influencers[0];return <>
  <div className="breadcrumb"><Link href="/influenciadores">Influenciadores</Link><span>/</span><span>{i.name}</span></div>
  <div className="page-head"><div style={{display:'flex',gap:14,alignItems:'center'}}><div className="client-logo" style={{width:52,height:52}}>{i.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><div className="eyebrow">Creator · {i.niche}</div><h1 className="page-title" style={{fontSize:24}}>{i.name}</h1><p className="page-subtitle">{i.handle} · {i.followers} seguidores · {i.city}</p></div></div><div className="head-actions"><button className="secondary-btn">Editar cadastro</button><button className="primary-btn keep-text">Nova participação</button></div></div>
  <div className="tabs"><a className="tab active">Resumo</a><a className="tab">Dados</a><a className="tab">Campanhas</a><a className="tab">Contratos</a><a className="tab">Arquivos</a><a className="tab">Histórico</a></div>
  <div className="two-col"><section className="panel"><div className="panel-head"><div><div className="panel-title">Dados centrais</div><div className="panel-sub">Cadastro único usado por campanhas e contratos.</div></div><Badge tone="green">Cadastro completo</Badge></div><div className="panel-body"><div className="details-grid"><div className="detail-box"><span>Nome completo</span><strong>{i.name}</strong></div><div className="detail-box"><span>CPF</span><strong>***.***.***-**</strong></div><div className="detail-box"><span>CNPJ</span><strong>**.***.***/****-**</strong></div><div className="detail-box"><span>E-mail</span><strong>creator@email.com</strong></div><div className="detail-box"><span>WhatsApp</span><strong>(11) 9****-****</strong></div><div className="detail-box"><span>Endereço de envio</span><strong>{i.city}</strong></div><div className="detail-box"><span>Calçado</span><strong>37</strong></div><div className="detail-box"><span>Camiseta</span><strong>M</strong></div><div className="detail-box"><span>Calça</span><strong>38</strong></div></div></div></section><section className="panel"><div className="panel-head"><div><div className="panel-title">Participação atual</div><div className="panel-sub">{i.client} · {i.campaign}</div></div></div><div className="panel-body stack"><div className="detail-box"><span>Casting</span><strong>✓ Aprovado pelo cliente</strong></div><div className="detail-box"><span>Contrato</span><strong>{i.contract}</strong></div><div className="detail-box"><span>Produto</span><strong>Vans Knu Skool · 37 · enviado</strong></div><div className="detail-box"><span>Conteúdo</span><strong>V1 recebida · aguardando revisão interna</strong></div></div></section></div>
  <div className="two-col" style={{marginTop:16}}><section className="panel"><div className="panel-head"><div><div className="panel-title">Dados para contrato</div><div className="panel-sub">Tudo pronto para copiar, mas o contrato continua sob revisão humana.</div></div><button className="secondary-btn"><Copy size={14}/> Copiar bloco</button></div><div className="panel-body"><div className="details-grid"><div className="detail-box"><span>Contratada</span><strong>{i.name.toUpperCase()} ME</strong></div><div className="detail-box"><span>CNPJ</span><strong>**.***.***/****-**</strong></div><div className="detail-box"><span>Representante</span><strong>{i.name}</strong></div><div className="detail-box"><span>CPF representante</span><strong>***.***.***-**</strong></div><div className="detail-box"><span>Endereço</span><strong>Endereço cadastrado</strong></div><div className="detail-box"><span>Contato</span><strong>creator@email.com</strong></div></div></div></section><section className="panel"><div className="panel-head"><div><div className="panel-title">Atividade recente</div><div className="panel-sub">Histórico rastreável.</div></div><History size={16}/></div><div className="panel-body"><div className="activity"><div className="activity-dot"/><div><strong>Conteúdo V1 recebido</strong><span>Hoje · 13:42 · por Pedro</span></div></div><div className="activity"><div className="activity-dot"/><div><strong>Produto marcado como enviado</strong><span>10 ago · rastreio adicionado</span></div></div><div className="activity"><div className="activity-dot"/><div><strong>Contrato assinado anexado</strong><span>08 ago · Google Drive</span></div></div><div className="activity"><div className="activity-dot"/><div><strong>Aprovada no casting</strong><span>06 ago · pela marca</span></div></div></div></section></div>
</>}
