'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';
import { Badge } from '@/components/ui';
import { History, ExternalLink } from '@/components/icons';

type Influencer={id:string;full_name:string;stage_name:string|null;cpf:string|null;cnpj:string|null;company_name:string|null;trade_name:string|null;email:string;phone:string|null;instagram:string|null;tiktok:string|null;youtube:string|null;niche:string|null;instagram_followers:number|null;postal_code:string|null;street:string|null;street_number:string|null;complement:string|null;district:string|null;city:string|null;state:string|null;shoe_size:string|null;shirt_size:string|null;pants_size:string|null;status:string;notes:string|null};
type Participation={id:string;casting_stage:string;agreed_fee:number|null;campaigns?:{id:string;name:string;clients?:{name:string}|null}|null};
type Contract={id:string;status:string;external_document_url:string|null;campaigns?:{name:string}|null};
type Activity={id:number;event_type:string;description:string|null;created_at:string};

const statusLabel=(s:string)=>({new_intake:'Novo cadastro',active:'Ativo',in_campaign:'Em campanha',contract_pending:'Contrato pendente',incomplete:'Cadastro incompleto'}[s]||s);

export default function InfluencerDetail(){
 const params=useParams<{id:string}>();const id=params.id;const supabase=useMemo(()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;return u&&k?createBrowserClient(u,k):null},[]);
 const [i,setI]=useState<Influencer|null>(null);const [parts,setParts]=useState<Participation[]>([]);const [contracts,setContracts]=useState<Contract[]>([]);const [activities,setActivities]=useState<Activity[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{if(!supabase)return;const [iq,pq,cq,aq]=await Promise.all([
  supabase.from('influencers').select('id,full_name,stage_name,cpf,cnpj,company_name,trade_name,email,phone,instagram,tiktok,youtube,niche,instagram_followers,postal_code,street,street_number,complement,district,city,state,shoe_size,shirt_size,pants_size,status,notes').eq('id',id).maybeSingle(),
  supabase.from('campaign_influencers').select('id,casting_stage,agreed_fee,campaigns(id,name,clients(name))').eq('influencer_id',id).order('created_at',{ascending:false}),
  supabase.from('contracts').select('id,status,external_document_url,campaigns(name)').eq('influencer_id',id).order('created_at',{ascending:false}),
  supabase.from('activity_logs').select('id,event_type,description,created_at').eq('influencer_id',id).order('created_at',{ascending:false}).limit(10)
 ]);if(iq.error||!iq.data)setError(iq.error?.message||'Influenciador não encontrado.');else setI(iq.data as Influencer);setParts((pq.data||[]) as unknown as Participation[]);setContracts((cq.data||[]) as unknown as Contract[]);setActivities((aq.data||[]) as Activity[]);setLoading(false)})()},[supabase,id]);
 if(loading)return <div className="panel"><div className="panel-body">Carregando creator…</div></div>;if(error||!i)return <div className="panel"><div className="panel-body">{error||'Creator não encontrado.'}</div></div>;
 const initials=i.full_name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();const address=[i.street,i.street_number,i.complement,i.district,i.city,i.state].filter(Boolean).join(', ');const current=parts[0];
 return <>
  <div className="breadcrumb"><Link href="/influenciadores">Influenciadores</Link><span>/</span><span>{i.stage_name||i.full_name}</span></div>
  <div className="page-head"><div style={{display:'flex',gap:14,alignItems:'center'}}><div className="client-logo" style={{width:52,height:52}}>{initials}</div><div><div className="eyebrow">Creator · {i.niche||'sem nicho'}</div><h1 className="page-title" style={{fontSize:24}}>{i.stage_name||i.full_name}</h1><p className="page-subtitle">{i.instagram||'sem @'} · {i.instagram_followers?.toLocaleString('pt-BR')||'—'} seguidores · {[i.city,i.state].filter(Boolean).join('/')||'local não informado'}</p></div></div><div className="head-actions"><Badge tone={i.status==='new_intake'?'blue':'green'}>{statusLabel(i.status)}</Badge></div></div>
  <div className="two-col"><section className="panel"><div className="panel-head"><div><div className="panel-title">Dados centrais</div><div className="panel-sub">Cadastro único usado por campanhas, contratos e logística.</div></div></div><div className="panel-body"><div className="details-grid"><div className="detail-box"><span>Nome completo</span><strong>{i.full_name}</strong></div><div className="detail-box"><span>CPF</span><strong>{i.cpf||'—'}</strong></div><div className="detail-box"><span>CNPJ</span><strong>{i.cnpj||'—'}</strong></div><div className="detail-box"><span>E-mail</span><strong>{i.email}</strong></div><div className="detail-box"><span>WhatsApp</span><strong>{i.phone||'—'}</strong></div><div className="detail-box"><span>Endereço de envio</span><strong>{address||'—'}</strong></div><div className="detail-box"><span>Calçado</span><strong>{i.shoe_size||'—'}</strong></div><div className="detail-box"><span>Camiseta</span><strong>{i.shirt_size||'—'}</strong></div><div className="detail-box"><span>Calça</span><strong>{i.pants_size||'—'}</strong></div></div></div></section>
  <section className="panel"><div className="panel-head"><div><div className="panel-title">Participação atual</div><div className="panel-sub">{current?.campaigns?.clients?.name||'Sem cliente'} · {current?.campaigns?.name||'Sem campanha ativa'}</div></div></div><div className="panel-body stack"><div className="detail-box"><span>Casting</span><strong>{current?.casting_stage||'—'}</strong></div><div className="detail-box"><span>Cachê acordado</span><strong>{current?.agreed_fee!=null?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(current.agreed_fee):'—'}</strong></div><div className="detail-box"><span>Contratos</span><strong>{contracts.length}</strong></div></div></section></div>
  <div className="two-col" style={{marginTop:16}}><section className="panel"><div className="panel-head"><div><div className="panel-title">Dados para contrato</div><div className="panel-sub">Informações reais disponíveis para revisão humana.</div></div></div><div className="panel-body"><div className="details-grid"><div className="detail-box"><span>Contratada</span><strong>{i.company_name||i.trade_name||i.full_name}</strong></div><div className="detail-box"><span>CNPJ</span><strong>{i.cnpj||'—'}</strong></div><div className="detail-box"><span>Representante</span><strong>{i.full_name}</strong></div><div className="detail-box"><span>CPF representante</span><strong>{i.cpf||'—'}</strong></div><div className="detail-box"><span>Endereço</span><strong>{address||'—'}</strong></div><div className="detail-box"><span>Contato</span><strong>{i.email}{i.phone?` · ${i.phone}`:''}</strong></div></div></div></section>
  <section className="panel"><div className="panel-head"><div><div className="panel-title">Atividade recente</div><div className="panel-sub">Histórico rastreável.</div></div><History size={16}/></div><div className="panel-body">{activities.length===0?<div>Nenhuma atividade registrada.</div>:activities.map(a=><div className="activity" key={a.id}><div className="activity-dot"/><div><strong>{a.description||a.event_type}</strong><span>{new Date(a.created_at).toLocaleString('pt-BR')}</span></div></div>)}</div></section></div>
  <section className="panel" style={{marginTop:16}}><div className="panel-head"><div><div className="panel-title">Contratos</div><div className="panel-sub">Registros ligados a este creator.</div></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Campanha</th><th>Status</th><th>Documento</th></tr></thead><tbody>{contracts.length===0?<tr><td colSpan={3}>Nenhum contrato registrado.</td></tr>:contracts.map(c=><tr key={c.id}><td>{c.campaigns?.name||'—'}</td><td><Badge>{c.status}</Badge></td><td>{c.external_document_url?<a href={c.external_document_url} target="_blank" rel="noreferrer" className="ghost-btn">Abrir <ExternalLink size={12}/></a>:'—'}</td></tr>)}</tbody></table></div></section>
 </>;
}
