'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';
import { Badge, MetricCard, Progress } from '@/components/ui';
import { Users, UserCheck, FileCheck2, Send, MoreHorizontal } from '@/components/icons';

type Campaign={id:string;name:string;status:string;phase:string;objective:string|null;description:string|null;audience:string|null;platforms:string[]|null;starts_at:string|null;ends_at:string|null;budget_total:number|null;client_id:string;clients?:{name:string}|null};
type Creator={id:string;casting_stage:string;proposed_fee:number|null;agreed_fee:number|null;negotiation_status:string|null;influencers?:{id:string;full_name:string;instagram:string|null}|null};

const stageTone=(s:string)=>s==='confirmed'?'green':s==='approved'?'blue':s==='negotiation'?'amber':s==='rejected'?'red':'slate';
const stageLabel=(s:string)=>({mapped:'Mapeado',internal_review:'Análise interna',selected:'Selecionado',sent_to_client:'Enviado cliente',approved:'Aprovado',rejected:'Reprovado',reserve:'Reserva',negotiation:'Negociação',confirmed:'Confirmado'}[s]||s);
const phaseProgress=(p:string)=>({briefing:10,casting:28,approval:42,negotiation:56,contract:68,content:80,publication:92,completed:100}[p]||15);

export default function CampaignWorkspace(){
 const params=useParams<{id:string}>();const id=params.id;const supabase=useMemo(()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;return u&&k?createBrowserClient(u,k):null},[]);
 const [campaign,setCampaign]=useState<Campaign|null>(null);const [creators,setCreators]=useState<Creator[]>([]);const [contracts,setContracts]=useState(0);const [published,setPublished]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{if(!supabase)return;const [cq,crq,coq,dq]=await Promise.all([
  supabase.from('campaigns').select('id,name,status,phase,objective,description,audience,platforms,starts_at,ends_at,budget_total,client_id,clients(name)').eq('id',id).maybeSingle(),
  supabase.from('campaign_influencers').select('id,casting_stage,proposed_fee,agreed_fee,negotiation_status,influencers(id,full_name,instagram)').eq('campaign_id',id).order('created_at'),
  supabase.from('contracts').select('*',{count:'exact',head:true}).eq('campaign_id',id).in('status',['signed','complete']),
  supabase.from('deliverables').select('*',{count:'exact',head:true}).eq('campaign_id',id).eq('status','published')
 ]);if(cq.error||!cq.data)setError(cq.error?.message||'Campanha não encontrada.');else setCampaign(cq.data as unknown as Campaign);setCreators((crq.data||[]) as unknown as Creator[]);setContracts(coq.count||0);setPublished(dq.count||0);setLoading(false)})()},[supabase,id]);
 if(loading)return <div className="panel"><div className="panel-body">Carregando campanha…</div></div>;if(error||!campaign)return <div className="panel"><div className="panel-body">{error||'Campanha não encontrada.'}</div></div>;
 const mapped=creators.length,approved=creators.filter(c=>['approved','negotiation','confirmed'].includes(c.casting_stage)).length,confirmed=creators.filter(c=>c.casting_stage==='confirmed').length,progress=phaseProgress(campaign.phase);
 return <>
  <div className="breadcrumb"><Link href="/clientes">Clientes</Link><span>/</span><Link href={`/clientes/${campaign.client_id}`}>{campaign.clients?.name||'Cliente'}</Link><span>/</span><span>{campaign.name}</span></div>
  <div className="page-head"><div><div className="eyebrow">{campaign.clients?.name||'Cliente'} · campanha</div><h1 className="page-title">{campaign.name}</h1><p className="page-subtitle">{campaign.phase}{campaign.ends_at?` · prazo ${new Date(campaign.ends_at+'T12:00:00').toLocaleDateString('pt-BR')}`:''}</p></div><div className="head-actions"><Link href="/influenciadores" className="primary-btn">Adicionar creator</Link></div></div>
  <div className="grid-metrics"><MetricCard label="Mapeados" value={mapped} meta="participações no casting" icon={<Users size={16}/>}/><MetricCard label="Aprovados" value={approved} meta="aprovados ou em negociação" icon={<UserCheck size={16}/>}/><MetricCard label="Contratos assinados" value={contracts} meta={`${confirmed} creators confirmados`} icon={<FileCheck2 size={16}/>}/><MetricCard label="Publicados" value={published} meta={`${progress}% da etapa geral`} icon={<Send size={16}/>} accent/></div>
  <section className="panel" style={{marginBottom:16}}><div className="panel-head"><div><div className="panel-title">Fluxo da campanha</div><div className="panel-sub">Status operacional consolidado.</div></div><Badge tone={campaign.status==='active'?'green':'blue'}>{campaign.status}</Badge></div><div className="panel-body"><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:12,alignItems:'center'}}><Progress value={progress}/><strong>{progress}%</strong></div></div></section>
  <div className="two-col"><section className="panel"><div className="panel-head"><div><div className="panel-title">Creators da campanha</div><div className="panel-sub">Casting e negociação na mesma visão.</div></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Creator</th><th>Casting</th><th>Negociação</th><th>Cachê proposto</th><th>Cachê acordado</th><th></th></tr></thead><tbody>{creators.length===0?<tr><td colSpan={6}>Nenhum creator ligado à campanha.</td></tr>:creators.map(i=><tr key={i.id}><td><Link href={`/influenciadores/${i.influencers?.id}`} className="person" style={{textDecoration:'none',color:'inherit'}}><div className="mini-avatar">{(i.influencers?.full_name||'CR').split(/\s+/).map(x=>x[0]).join('').slice(0,2)}</div><div className="name-cell"><strong>{i.influencers?.full_name||'Creator'}</strong><span>{i.influencers?.instagram||'sem @'}</span></div></Link></td><td><Badge tone={stageTone(i.casting_stage) as any}>{stageLabel(i.casting_stage)}</Badge></td><td>{i.negotiation_status||'—'}</td><td>{i.proposed_fee!=null?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(i.proposed_fee):'—'}</td><td>{i.agreed_fee!=null?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(i.agreed_fee):'—'}</td><td><MoreHorizontal size={15}/></td></tr>)}</tbody></table></div></section>
  <section className="panel"><div className="panel-head"><div><div className="panel-title">Briefing operacional</div><div className="panel-sub">Dados estruturados da campanha.</div></div></div><div className="panel-body stack"><div className="detail-box"><span>Objetivo</span><strong>{campaign.objective||'—'}</strong></div><div className="detail-box"><span>Público</span><strong>{campaign.audience||'—'}</strong></div><div className="detail-box"><span>Plataformas</span><strong>{campaign.platforms?.join(' · ')||'—'}</strong></div><div className="detail-box"><span>Orçamento</span><strong>{campaign.budget_total!=null?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(campaign.budget_total):'—'}</strong></div><div className="detail-box"><span>Descrição</span><strong>{campaign.description||'—'}</strong></div></div></section></div>
 </>;
}
