'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';
import { Badge, MetricCard, Progress } from '@/components/ui';
import { Users, UserCheck, FileCheck2, Send, Plus, X } from '@/components/icons';

type Campaign={id:string;name:string;status:string;phase:string;objective:string|null;description:string|null;audience:string|null;platforms:string[]|null;starts_at:string|null;ends_at:string|null;budget_total:number|null;client_id:string;organization_id:string;clients?:{name:string}|null};
type Creator={id:string;casting_stage:string;proposed_fee:number|null;agreed_fee:number|null;negotiation_status:string|null;influencers?:{id:string;full_name:string;instagram:string|null}|null};
type InfluencerOption={id:string;full_name:string;instagram:string|null;niche:string|null};

const stages=['mapped','internal_review','selected','sent_to_client','approved','rejected','reserve','negotiation','confirmed'] as const;
const phases=['briefing','casting','approval','negotiation','contract','content','publication','completed'] as const;
const stageTone=(s:string)=>s==='confirmed'?'green':s==='approved'?'blue':s==='negotiation'?'amber':s==='rejected'?'red':'slate';
const stageLabel=(s:string)=>({mapped:'Mapeado',internal_review:'Análise interna',selected:'Selecionado',sent_to_client:'Enviado cliente',approved:'Aprovado',rejected:'Reprovado',reserve:'Reserva',negotiation:'Negociação',confirmed:'Confirmado'}[s]||s);
const phaseLabel=(s:string)=>({briefing:'Briefing',casting:'Casting',approval:'Aprovação cliente',negotiation:'Negociação',contract:'Contratos',content:'Conteúdo',publication:'Publicação',completed:'Concluída'}[s]||s);
const phaseProgress=(p:string)=>({briefing:10,casting:28,approval:42,negotiation:56,contract:68,content:80,publication:92,completed:100}[p]||15);

export default function CampaignWorkspace(){
 const params=useParams<{id:string}>();const id=String(params.id);const supabase=useMemo(()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;return u&&k?createBrowserClient(u,k):null},[]);
 const [campaign,setCampaign]=useState<Campaign|null>(null);const [creators,setCreators]=useState<Creator[]>([]);const [allInfluencers,setAllInfluencers]=useState<InfluencerOption[]>([]);const [contracts,setContracts]=useState(0);const [published,setPublished]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [openAdd,setOpenAdd]=useState(false);const [editing,setEditing]=useState(false);const [selected,setSelected]=useState('');const [proposedFee,setProposedFee]=useState('');const [saving,setSaving]=useState(false);const [campaignForm,setCampaignForm]=useState({name:'',status:'planning',phase:'briefing',objective:'',description:'',audience:'',platforms:'',starts_at:'',ends_at:'',budget_total:''});
 async function load(){if(!supabase)return;setLoading(true);setError('');const [cq,crq,coq,dq,iq]=await Promise.all([
  supabase.from('campaigns').select('id,name,status,phase,objective,description,audience,platforms,starts_at,ends_at,budget_total,client_id,organization_id,clients(name)').eq('id',id).maybeSingle(),
  supabase.from('campaign_influencers').select('id,casting_stage,proposed_fee,agreed_fee,negotiation_status,influencers(id,full_name,instagram)').eq('campaign_id',id).order('created_at'),
  supabase.from('contracts').select('*',{count:'exact',head:true}).eq('campaign_id',id).in('status',['signed','complete']),
  supabase.from('deliverables').select('*',{count:'exact',head:true}).eq('campaign_id',id).eq('status','published'),
  supabase.from('influencers').select('id,full_name,instagram,niche').order('full_name')
 ]);if(cq.error||!cq.data)setError(cq.error?.message||'Campanha não encontrada.');else{const c=cq.data as unknown as Campaign;setCampaign(c);setCampaignForm({name:c.name,status:c.status,phase:c.phase,objective:c.objective||'',description:c.description||'',audience:c.audience||'',platforms:c.platforms?.join(', ')||'',starts_at:c.starts_at||'',ends_at:c.ends_at||'',budget_total:c.budget_total?.toString()||''})}setCreators((crq.data||[]) as unknown as Creator[]);setContracts(coq.count||0);setPublished(dq.count||0);setAllInfluencers((iq.data||[]) as InfluencerOption[]);setLoading(false)}
 useEffect(()=>{load()},[supabase,id]);
 async function saveCampaign(e:React.FormEvent){e.preventDefault();if(!supabase||!campaign)return;setSaving(true);setError('');const platforms=campaignForm.platforms.split(',').map(v=>v.trim()).filter(Boolean);const {error:e2}=await supabase.from('campaigns').update({name:campaignForm.name.trim(),status:campaignForm.status,phase:campaignForm.phase,objective:campaignForm.objective.trim()||null,description:campaignForm.description.trim()||null,audience:campaignForm.audience.trim()||null,platforms,starts_at:campaignForm.starts_at||null,ends_at:campaignForm.ends_at||null,budget_total:campaignForm.budget_total?Number(campaignForm.budget_total):null,updated_at:new Date().toISOString()}).eq('id',campaign.id);setSaving(false);if(e2){setError(e2.message);return}setEditing(false);await load()}
 async function addCreator(e:React.FormEvent){e.preventDefault();if(!supabase||!campaign||!selected)return;setSaving(true);setError('');const {error:e2}=await supabase.from('campaign_influencers').insert({organization_id:campaign.organization_id,campaign_id:campaign.id,influencer_id:selected,casting_stage:'mapped',proposed_fee:proposedFee?Number(proposedFee):null,current_step:'casting'});setSaving(false);if(e2){setError(e2.message);return}setSelected('');setProposedFee('');setOpenAdd(false);await load()}
 async function changeStage(rowId:string,stage:string){if(!supabase)return;await supabase.from('campaign_influencers').update({casting_stage:stage,current_step:stage,updated_at:new Date().toISOString()}).eq('id',rowId);await load()}
 async function changeFee(rowId:string,current:number|null,field:'proposed_fee'|'agreed_fee'){if(!supabase)return;const value=window.prompt(field==='proposed_fee'?'Cachê proposto (R$):':'Cachê acordado (R$):',current?.toString()||'');if(value===null)return;const parsed=value.trim()===''?null:Number(value.replace(',','.'));if(parsed!==null&&!Number.isFinite(parsed))return;await supabase.from('campaign_influencers').update({[field]:parsed,updated_at:new Date().toISOString()}).eq('id',rowId);await load()}
 if(loading)return <div className="panel"><div className="panel-body">Carregando campanha…</div></div>;if(error&&!campaign)return <div className="panel"><div className="panel-body">{error}</div></div>;if(!campaign)return null;
 const mapped=creators.length,approved=creators.filter(c=>['approved','negotiation','confirmed'].includes(c.casting_stage)).length,confirmed=creators.filter(c=>c.casting_stage==='confirmed').length,progress=phaseProgress(campaign.phase);const used=new Set(creators.map(c=>c.influencers?.id).filter(Boolean));const available=allInfluencers.filter(i=>!used.has(i.id));
 return <>
  <div className="breadcrumb"><Link href="/clientes">Clientes</Link><span>/</span><Link href={`/clientes/${campaign.client_id}`}>{campaign.clients?.name||'Cliente'}</Link><span>/</span><span>{campaign.name}</span></div>
  <div className="page-head"><div><div className="eyebrow">{campaign.clients?.name||'Cliente'} · campanha</div><h1 className="page-title">{campaign.name}</h1><p className="page-subtitle">{phaseLabel(campaign.phase)}{campaign.ends_at?` · prazo ${new Date(campaign.ends_at+'T12:00:00').toLocaleDateString('pt-BR')}`:''}</p></div><div className="head-actions"><button className="secondary-btn" onClick={()=>setEditing(v=>!v)}>{editing?<X size={14}/>:null}{editing?'Fechar edição':'Editar campanha'}</button><button className="primary-btn keep-text" onClick={()=>setOpenAdd(v=>!v)}>{openAdd?<X size={16}/>:<Plus size={16}/>} {openAdd?'Fechar casting':'Adicionar creator'}</button></div></div>
  {error&&<div className="success-box" style={{background:'#fff0f2',color:'#ba3b4d',marginBottom:14}}>{error}</div>}
  {editing&&<form className="form-card" onSubmit={saveCampaign} style={{marginBottom:16}}><div className="form-section" style={{marginBottom:0,paddingBottom:0,borderBottom:0}}><h3>Editar campanha</h3><p>Atualize briefing, fase, datas e orçamento sem sair do workspace.</p><div className="form-grid three"><div className="field"><label>Nome *</label><input required value={campaignForm.name} onChange={e=>setCampaignForm({...campaignForm,name:e.target.value})}/></div><div className="field"><label>Status</label><select value={campaignForm.status} onChange={e=>setCampaignForm({...campaignForm,status:e.target.value})}><option value="planning">Planejamento</option><option value="active">Ativa</option><option value="paused">Pausada</option><option value="completed">Concluída</option></select></div><div className="field"><label>Etapa</label><select value={campaignForm.phase} onChange={e=>setCampaignForm({...campaignForm,phase:e.target.value})}>{phases.map(p=><option key={p} value={p}>{phaseLabel(p)}</option>)}</select></div><div className="field"><label>Início</label><input type="date" value={campaignForm.starts_at} onChange={e=>setCampaignForm({...campaignForm,starts_at:e.target.value})}/></div><div className="field"><label>Fim</label><input type="date" value={campaignForm.ends_at} onChange={e=>setCampaignForm({...campaignForm,ends_at:e.target.value})}/></div><div className="field"><label>Orçamento</label><input type="number" min="0" step="0.01" value={campaignForm.budget_total} onChange={e=>setCampaignForm({...campaignForm,budget_total:e.target.value})}/></div><div className="field"><label>Objetivo</label><input value={campaignForm.objective} onChange={e=>setCampaignForm({...campaignForm,objective:e.target.value})}/></div><div className="field"><label>Público</label><input value={campaignForm.audience} onChange={e=>setCampaignForm({...campaignForm,audience:e.target.value})}/></div><div className="field"><label>Plataformas</label><input value={campaignForm.platforms} onChange={e=>setCampaignForm({...campaignForm,platforms:e.target.value})} placeholder="Instagram, TikTok, YouTube"/></div><div className="field full"><label>Descrição / briefing operacional</label><textarea value={campaignForm.description} onChange={e=>setCampaignForm({...campaignForm,description:e.target.value})}/></div></div><div className="submit-row"><span className="privacy-note">A etapa controla o progresso exibido no dashboard.</span><button className="primary-btn keep-text" disabled={saving}>{saving?'Salvando…':'Salvar campanha'}</button></div></div></form>}
  {openAdd&&<form className="form-card" onSubmit={addCreator} style={{marginBottom:16}}><div className="form-section" style={{marginBottom:0,paddingBottom:0,borderBottom:0}}><h3>Adicionar ao casting</h3><p>Escolha um creator já cadastrado. Ele entra como “Mapeado” e pode avançar pelo funil abaixo.</p><div className="form-grid"><div className="field"><label>Creator *</label><select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecione</option>{available.map(i=><option value={i.id} key={i.id}>{i.full_name}{i.instagram?` · ${i.instagram}`:''}{i.niche?` · ${i.niche}`:''}</option>)}</select></div><div className="field"><label>Cachê proposto</label><input type="number" min="0" step="0.01" value={proposedFee} onChange={e=>setProposedFee(e.target.value)}/></div></div><div className="submit-row"><span className="privacy-note">Não duplica creator já presente nesta campanha.</span><button className="primary-btn keep-text" disabled={saving||available.length===0}>{saving?'Adicionando…':available.length===0?'Todos já adicionados':'Adicionar ao casting'}</button></div></div></form>}
  <div className="grid-metrics"><MetricCard label="Mapeados" value={mapped} meta="participações no casting" icon={<Users size={16}/>}/><MetricCard label="Aprovados" value={approved} meta="aprovados ou em negociação" icon={<UserCheck size={16}/>}/><MetricCard label="Contratos assinados" value={contracts} meta={`${confirmed} creators confirmados`} icon={<FileCheck2 size={16}/>}/><MetricCard label="Publicados" value={published} meta={`${progress}% da etapa geral`} icon={<Send size={16}/>} accent/></div>
  <section className="panel" style={{marginBottom:16}}><div className="panel-head"><div><div className="panel-title">Fluxo da campanha</div><div className="panel-sub">Status operacional consolidado.</div></div><Badge tone={campaign.status==='active'?'green':'blue'}>{campaign.status}</Badge></div><div className="panel-body"><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:12,alignItems:'center'}}><Progress value={progress}/><strong>{progress}%</strong></div></div></section>
  <div className="two-col"><section className="panel"><div className="panel-head"><div><div className="panel-title">Creators da campanha</div><div className="panel-sub">Casting, negociação e cachê editáveis na mesma visão.</div></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Creator</th><th>Casting</th><th>Negociação</th><th>Cachê proposto</th><th>Cachê acordado</th></tr></thead><tbody>{creators.length===0?<tr><td colSpan={5}>Nenhum creator ligado à campanha.</td></tr>:creators.map(i=><tr key={i.id}><td><Link href={`/influenciadores/${i.influencers?.id}`} className="person" style={{textDecoration:'none',color:'inherit'}}><div className="mini-avatar">{(i.influencers?.full_name||'CR').split(/\s+/).map(x=>x[0]).join('').slice(0,2)}</div><div className="name-cell"><strong>{i.influencers?.full_name||'Creator'}</strong><span>{i.influencers?.instagram||'sem @'}</span></div></Link></td><td><select value={i.casting_stage} onChange={e=>changeStage(i.id,e.target.value)} style={{border:'1px solid #e1e3eb',borderRadius:9,padding:'7px 8px',background:'#fff'}}>{stages.map(s=><option key={s} value={s}>{stageLabel(s)}</option>)}</select><div style={{marginTop:5}}><Badge tone={stageTone(i.casting_stage) as any}>{stageLabel(i.casting_stage)}</Badge></div></td><td>{i.negotiation_status||'—'}</td><td><button className="ghost-btn" onClick={()=>changeFee(i.id,i.proposed_fee,'proposed_fee')}>{i.proposed_fee!=null?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(i.proposed_fee):'Definir'}</button></td><td><button className="ghost-btn" onClick={()=>changeFee(i.id,i.agreed_fee,'agreed_fee')}>{i.agreed_fee!=null?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(i.agreed_fee):'Definir'}</button></td></tr>)}</tbody></table></div></section>
  <section className="panel"><div className="panel-head"><div><div className="panel-title">Briefing operacional</div><div className="panel-sub">Dados estruturados da campanha.</div></div></div><div className="panel-body stack"><div className="detail-box"><span>Objetivo</span><strong>{campaign.objective||'—'}</strong></div><div className="detail-box"><span>Público</span><strong>{campaign.audience||'—'}</strong></div><div className="detail-box"><span>Plataformas</span><strong>{campaign.platforms?.join(' · ')||'—'}</strong></div><div className="detail-box"><span>Orçamento</span><strong>{campaign.budget_total!=null?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(campaign.budget_total):'—'}</strong></div><div className="detail-box"><span>Descrição</span><strong>{campaign.description||'—'}</strong></div></div></section></div>
 </>;
}
