'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';
import { Badge, MetricCard, Progress } from '@/components/ui';
import { ArrowUpRight, Clock3, Users, Megaphone, FileCheck2, X } from '@/components/icons';

type Client={id:string;name:string;legal_name:string|null;cnpj:string|null;category:string|null;website:string|null;instagram:string|null;status:string;notes:string|null};
type Campaign={id:string;name:string;status:string;phase:string;ends_at:string|null};
type Task={id:string;title:string;type:string;waiting_for:string;due_at:string|null};

export default function ClientWorkspace(){
 const params=useParams<{id:string}>(); const id=String(params.id);
 const supabase=useMemo(()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;return u&&k?createBrowserClient(u,k):null},[]);
 const [client,setClient]=useState<Client|null>(null); const [campaigns,setCampaigns]=useState<Campaign[]>([]); const [tasks,setTasks]=useState<Task[]>([]); const [creatorCount,setCreatorCount]=useState(0); const [contractCount,setContractCount]=useState(0); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [editing,setEditing]=useState(false);const [saving,setSaving]=useState(false);const [form,setForm]=useState({name:'',legal_name:'',cnpj:'',category:'',website:'',instagram:'',status:'active',notes:''});
 async function load(){if(!supabase)return;setLoading(true);setError('');const [cq,camq,tq,ciq,coq]=await Promise.all([
   supabase.from('clients').select('id,name,legal_name,cnpj,category,website,instagram,status,notes').eq('id',id).maybeSingle(),
   supabase.from('campaigns').select('id,name,status,phase,ends_at').eq('client_id',id).order('created_at',{ascending:false}),
   supabase.from('tasks').select('id,title,type,waiting_for,due_at').eq('client_id',id).neq('status','done').order('due_at',{ascending:true,nullsFirst:false}).limit(6),
   supabase.from('campaign_influencers').select('influencer_id,campaigns!inner(client_id)',{count:'exact',head:true}).eq('campaigns.client_id',id),
   supabase.from('contracts').select('*',{count:'exact',head:true}).eq('client_id',id).neq('status','complete')
 ]);if(cq.error||!cq.data)setError(cq.error?.message||'Cliente não encontrado.');else{const c=cq.data as Client;setClient(c);setForm({name:c.name,legal_name:c.legal_name||'',cnpj:c.cnpj||'',category:c.category||'',website:c.website||'',instagram:c.instagram||'',status:c.status,notes:c.notes||''})}setCampaigns((camq.data||[]) as Campaign[]);setTasks((tq.data||[]) as Task[]);setCreatorCount(ciq.count||0);setContractCount(coq.count||0);setLoading(false)}
 useEffect(()=>{load()},[supabase,id]);
 async function saveClient(e:React.FormEvent){e.preventDefault();if(!supabase||!client)return;setSaving(true);setError('');const {error:e2}=await supabase.from('clients').update({name:form.name.trim(),legal_name:form.legal_name.trim()||null,cnpj:form.cnpj.trim()||null,category:form.category.trim()||null,website:form.website.trim()||null,instagram:form.instagram.trim()||null,status:form.status,notes:form.notes.trim()||null,updated_at:new Date().toISOString()}).eq('id',client.id);setSaving(false);if(e2){setError(e2.message);return}setEditing(false);await load()}
 if(loading)return <div className="panel"><div className="panel-body">Carregando workspace…</div></div>;
 if(error&&!client)return <><div className="breadcrumb"><Link href="/clientes">Clientes</Link></div><div className="panel"><div className="panel-body">{error}</div></div></>;
 if(!client)return null;
 const initials=client.name.split(/\s+/).slice(0,2).map(v=>v[0]).join('').toUpperCase(); const active=campaigns.filter(c=>c.status!=='completed').length;
 const phaseProgress=(p:string)=>({briefing:10,casting:28,approval:42,negotiation:56,contract:68,content:80,publication:92,completed:100}[p]||15);
 return <>
  <div className="breadcrumb"><Link href="/clientes">Clientes</Link><span>/</span><span>{client.name}</span></div>
  <div className="workspace-hero"><div className="workspace-hero-top"><div className="workspace-client"><div className="client-logo">{initials}</div><div><h1>{client.name}</h1><p>{client.category||'Categoria não informada'}{client.instagram?` · ${client.instagram}`:''}</p></div></div><div className="head-actions"><button className="secondary-btn" onClick={()=>setEditing(v=>!v)}>{editing?<X size={14}/>:null}{editing?'Fechar edição':'Editar cliente'}</button><Link href="/campanhas" className="primary-btn">Nova campanha</Link></div></div><div className="workspace-tags"><Badge tone={client.status==='active'?'green':'slate'}>{client.status==='active'?'Cliente ativo':client.status}</Badge><Badge>{active} campanhas abertas</Badge><Badge>{creatorCount} participações de creators</Badge></div></div>
  {editing&&<form className="form-card" onSubmit={saveClient} style={{marginBottom:16}}><div className="form-section" style={{marginBottom:0,paddingBottom:0,borderBottom:0}}><h3>Editar cliente</h3><p>Atualize os dados permanentes da marca.</p><div className="form-grid three"><div className="field"><label>Nome *</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Razão social</label><input value={form.legal_name} onChange={e=>setForm({...form,legal_name:e.target.value})}/></div><div className="field"><label>CNPJ</label><input value={form.cnpj} onChange={e=>setForm({...form,cnpj:e.target.value})}/></div><div className="field"><label>Categoria</label><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></div><div className="field"><label>Instagram</label><input value={form.instagram} onChange={e=>setForm({...form,instagram:e.target.value})}/></div><div className="field"><label>Site</label><input value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/></div><div className="field"><label>Status</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Ativo</option><option value="paused">Pausado</option><option value="inactive">Inativo</option></select></div><div className="field full"><label>Observações</label><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div></div><div className="submit-row"><span className="privacy-note">As mudanças atualizam o workspace imediatamente.</span><button className="primary-btn keep-text" disabled={saving}>{saving?'Salvando…':'Salvar alterações'}</button></div></div></form>}
  {error&&<div className="success-box" style={{background:'#fff0f2',color:'#ba3b4d',marginBottom:14}}>{error}</div>}
  <div className="grid-metrics"><MetricCard label="Campanhas abertas" value={active} icon={<Megaphone size={16}/>}/><MetricCard label="Creators no histórico" value={creatorCount} icon={<Users size={16}/>}/><MetricCard label="Pendências" value={tasks.length} icon={<Clock3 size={16}/>} accent/><MetricCard label="Contratos pendentes" value={contractCount} icon={<FileCheck2 size={16}/>}/></div>
  <div className="overview-grid"><section className="panel"><div className="panel-head"><div><div className="panel-title">Campanhas da marca</div><div className="panel-sub">Dados reais ligados a este cliente.</div></div><Link href="/campanhas" className="ghost-btn">Abrir todas <ArrowUpRight size={14}/></Link></div>{campaigns.length===0?<div className="panel-body">Nenhuma campanha cadastrada.</div>:campaigns.map(c=><Link href={`/campanhas/${c.id}`} className="campaign-card" key={c.id} style={{display:'block',textDecoration:'none',color:'inherit'}}><div className="campaign-row"><div><div className="campaign-name">{c.name}</div><div className="campaign-client">{c.phase}{c.ends_at?` · até ${new Date(c.ends_at+'T12:00:00').toLocaleDateString('pt-BR')}`:''}</div></div><Badge tone={c.status==='active'?'green':'blue'}>{c.status}</Badge></div><Progress value={phaseProgress(c.phase)}/></Link>)}</section>
  <section className="panel"><div className="panel-head"><div><div className="panel-title">Precisa de atenção</div><div className="panel-sub">Pendências abertas deste cliente.</div></div></div><div className="panel-body task-list">{tasks.length===0?<div>Nenhuma pendência aberta.</div>:tasks.map(t=><div className="task-row" key={t.id}><div className="task-icon"><Clock3 size={14}/></div><div><div className="task-title">{t.title}</div><div className="task-meta"><span>{t.type}</span><span>•</span><span>{t.waiting_for==='internal'?'Interno':`Aguardando ${t.waiting_for}`}</span></div></div><div className="task-due">{t.due_at?new Date(t.due_at).toLocaleDateString('pt-BR'):'Sem prazo'}</div></div>)}</div></section></div>
  <div className="panel" style={{marginTop:16}}><div className="panel-head"><div><div className="panel-title">Dados da marca</div><div className="panel-sub">Informações permanentes do cadastro.</div></div></div><div className="panel-body"><div className="details-grid"><div className="detail-box"><span>Razão social</span><strong>{client.legal_name||'—'}</strong></div><div className="detail-box"><span>CNPJ</span><strong>{client.cnpj||'—'}</strong></div><div className="detail-box"><span>Categoria</span><strong>{client.category||'—'}</strong></div><div className="detail-box"><span>Instagram</span><strong>{client.instagram||'—'}</strong></div><div className="detail-box"><span>Site</span><strong>{client.website||'—'}</strong></div><div className="detail-box"><span>Observações</span><strong>{client.notes||'—'}</strong></div></div></div></div>
 </>;
}
