import Link from 'next/link';
import { clients, campaigns, influencers, tasks } from '@/lib/demo-data';
import { Badge, MetricCard, Progress } from '@/components/ui';
import { ArrowUpRight, Plus, Clock3, Users, Megaphone, FileCheck2, Package, MoreHorizontal } from '@/components/icons';

export default async function ClientWorkspace({ params }: { params: Promise<{id:string}> }){
  const {id}=await params; const client=clients.find(c=>c.id===id)??clients[0];
  const clientCampaigns=campaigns.filter(c=>c.client===client.name); const clientInfluencers=influencers.filter(i=>i.client===client.name);
  return <>
    <div className="breadcrumb"><Link href="/clientes">Clientes</Link><span>/</span><span>{client.name}</span></div>
    <div className="workspace-hero"><div className="workspace-hero-top"><div className="workspace-client"><div className="client-logo">{client.initials}</div><div><h1>{client.name}</h1><p>{client.category} · Responsável: {client.owner}</p></div></div><div className="head-actions"><button className="secondary-btn">Editar cliente</button><button className="primary-btn keep-text"><Plus size={16}/> Nova campanha</button></div></div><div className="workspace-tags"><Badge>Cliente ativo</Badge><Badge>{client.activeCampaigns} campanhas ativas</Badge><Badge>{client.influencers} creators no histórico</Badge></div></div>
    <div className="tabs"><Link className="tab active" href="#">Visão geral</Link><Link className="tab" href="#campanhas">Campanhas</Link><Link className="tab" href="#creators">Influenciadores</Link><Link className="tab" href="#produtos">Produtos & envios</Link><Link className="tab" href="#contratos">Contratos</Link><Link className="tab" href="#arquivos">Arquivos</Link><Link className="tab" href="#historico">Histórico</Link></div>
    <div className="grid-metrics"><MetricCard label="Campanhas ativas" value={client.activeCampaigns} meta="1 em planejamento" icon={<Megaphone size={16}/>}/><MetricCard label="Creators ativos" value={clientInfluencers.length} meta="na operação atual" icon={<Users size={16}/>}/><MetricCard label="Pendências" value={client.pending} meta="3 precisam de ação interna" icon={<Clock3 size={16}/>} accent/><MetricCard label="Contratos" value="7/8" meta="1 ainda precisa ser preparado" icon={<FileCheck2 size={16}/>}/></div>
    <div className="overview-grid">
      <section className="panel" id="campanhas"><div className="panel-head"><div><div className="panel-title">Campanhas da marca</div><div className="panel-sub">Status consolidado da operação.</div></div><Link href="/campanhas" className="ghost-btn">Abrir todas <ArrowUpRight size={14}/></Link></div>{clientCampaigns.map(c=><Link href={`/campanhas/${c.id}`} className="campaign-card" key={c.id} style={{display:'block',textDecoration:'none',color:'inherit'}}><div className="campaign-row"><div><div className="campaign-name">{c.name}</div><div className="campaign-client">{c.phase} · prazo {c.deadline}</div></div><Badge tone={c.status==='Em execução'?'green':'blue'}>{c.status}</Badge></div><div className="campaign-stats"><div className="campaign-stat"><strong>{c.mapped}</strong><span>Mapeados</span></div><div className="campaign-stat"><strong>{c.sent}</strong><span>Cliente</span></div><div className="campaign-stat"><strong>{c.approved}</strong><span>Aprovados</span></div><div className="campaign-stat"><strong>{c.contracted}</strong><span>Contratos</span></div><div className="campaign-stat"><strong>{c.published}</strong><span>Postados</span></div></div><Progress value={c.progress}/></Link>)}</section>
      <section className="panel"><div className="panel-head"><div><div className="panel-title">Precisa de atenção</div><div className="panel-sub">Somente o que bloqueia ou atrasa este cliente.</div></div></div><div className="panel-body task-list">{tasks.filter(t=>t.client===client.name).slice(0,4).map(t=><div className="task-row" key={t.id}><div className="task-icon"><Clock3 size={14}/></div><div><div className="task-title">{t.title}</div><div className="task-meta"><span>{t.type}</span><span>•</span><span>Aguardando {t.waitingFor}</span></div></div><div className={`task-due ${t.status==='Atrasada'?'overdue':''}`}>{t.due}</div></div>)}</div></section>
    </div>
    <div className="two-col" style={{marginTop:16}}>
      <section className="panel" id="creators"><div className="panel-head"><div><div className="panel-title">Creators ligados à marca</div><div className="panel-sub">Histórico e situação atual sem duplicar cadastros.</div></div><button className="ghost-btn">Ver histórico</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Creator</th><th>Campanha</th><th>Status</th><th>Histórico</th><th></th></tr></thead><tbody>{clientInfluencers.map(i=><tr key={i.id}><td><div className="person"><div className="mini-avatar">{i.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div className="name-cell"><strong>{i.name}</strong><span>{i.handle}</span></div></div></td><td>{i.campaign}</td><td><Badge tone="green">{i.status}</Badge></td><td>{i.score}</td><td><MoreHorizontal size={15}/></td></tr>)}</tbody></table></div></section>
      <section className="panel"><div className="panel-head"><div><div className="panel-title">Diretrizes da marca</div><div className="panel-sub">Informações permanentes para acelerar novos castings.</div></div></div><div className="panel-body stack"><div className="detail-box"><span>Nichos preferidos</span><strong>Streetwear · Skate · Moda · Lifestyle · Música</strong></div><div className="detail-box"><span>Público prioritário</span><strong>18–30 · Brasil · Grandes centros urbanos</strong></div><div className="detail-box"><span>Regras frequentes</span><strong>Validar conflito com concorrentes antes de enviar ao cliente</strong></div><button className="secondary-btn">Editar diretrizes</button></div></section>
    </div>
  </>
}
