'use client';
import Link from 'next/link';
import { useEffect,useMemo,useState } from 'react';
import { getSupabaseBrowser } from '@/lib/supabase-browser';
import { PageHeader,Badge,EmptyState,SkeletonRows } from '@/components/ui';
import { Search,Plus,X,Building2,ArrowUpRight,Archive } from '@/components/icons';

type Client={id:string;name:string;category:string|null;status:string;instagram:string|null;website:string|null;created_at:string;campaigns?:{count:number}[]};
export default function Clientes(){
 const supabase=useMemo(()=>getSupabaseBrowser(),[]);
 const [items,setItems]=useState<Client[]>([]),[orgId,setOrgId]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[status,setStatus]=useState('active');
 const [form,setForm]=useState({name:'',category:'',instagram:'',website:'',legal_name:'',cnpj:''});
 async function load(){if(!supabase)return;setLoading(true);const {data:member}=await supabase.from('organization_members').select('organization_id').limit(1).maybeSingle();if(!member){setError('Usuário sem workspace.');setLoading(false);return}setOrgId(member.organization_id);const {data,error}=await supabase.from('clients').select('id,name,category,status,instagram,website,created_at').order('created_at',{ascending:false});if(error)setError(error.message);else setItems((data||[]) as Client[]);setLoading(false)}
 useEffect(()=>{load()},[supabase]);
 async function create(e:React.FormEvent){e.preventDefault();if(!supabase||!orgId)return;setSaving(true);const {error}=await supabase.from('clients').insert({organization_id:orgId,...form,name:form.name.trim(),category:form.category||null,instagram:form.instagram||null,website:form.website||null,legal_name:form.legal_name||null,cnpj:form.cnpj||null,status:'active'});if(error)setError(error.message);else{setOpen(false);setForm({name:'',category:'',instagram:'',website:'',legal_name:'',cnpj:''});await load()}setSaving(false)}
 const filtered=items.filter(i=>(status==='all'||i.status===status)&&`${i.name} ${i.category||''} ${i.instagram||''}`.toLowerCase().includes(query.toLowerCase()));
 return <><PageHeader eyebrow="Base da agência" title="Clientes" description="Cada marca funciona como um workspace próprio, com campanhas, creators, arquivos, contratos e histórico." action={<button className="primary-btn" onClick={()=>setOpen(v=>!v)}>{open?<X size={15}/>:<Plus size={15}/>} {open?'Fechar':'Novo cliente'}</button>}/>
 {open&&<form className="form-card" onSubmit={create} style={{marginBottom:14}}><div className="form-section"><h3>Novo cliente</h3><p>Cadastre o essencial. O restante pode ser completado dentro do workspace da marca.</p><div className="form-grid three"><div className="field"><label>Nome da marca *</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Razão social</label><input value={form.legal_name} onChange={e=>setForm({...form,legal_name:e.target.value})}/></div><div className="field"><label>CNPJ</label><input value={form.cnpj} onChange={e=>setForm({...form,cnpj:e.target.value})}/></div><div className="field"><label>Categoria</label><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></div><div className="field"><label>Instagram</label><input value={form.instagram} onChange={e=>setForm({...form,instagram:e.target.value})} placeholder="@marca"/></div><div className="field"><label>Site</label><input value={form.website} onChange={e=>setForm({...form,website:e.target.value})} placeholder="https://"/></div></div><div className="submit-row"><span className="privacy-note">O cliente será salvo no workspace atual.</span><button className="primary-btn" disabled={saving}>{saving?'Salvando...':'Salvar cliente'}</button></div></div></form>}
 <div className="toolbar"><div className="search-box"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente..."/></div><div className="view-switch"><button className={status==='active'?'active':''} onClick={()=>setStatus('active')}>Ativos</button><button className={status==='archived'?'active':''} onClick={()=>setStatus('archived')}>Arquivados</button><button className={status==='all'?'active':''} onClick={()=>setStatus('all')}>Todos</button></div></div>
 {error&&<div className="error-box" style={{marginBottom:12}}>{error}</div>}
 {loading?<div className="panel"><SkeletonRows count={6}/></div>:filtered.length===0?<div className="panel"><EmptyState icon={<Building2 size={21}/>} title="Nenhum cliente encontrado" description={query?'Tente outro termo ou remova os filtros.':'Cadastre a primeira marca para começar a organizar a operação.'} action={!query?<button className="primary-btn" onClick={()=>setOpen(true)}><Plus size={14}/> Novo cliente</button>:undefined}/></div>:<div className="client-grid">{filtered.map(c=><Link href={`/clientes/${c.id}`} className="client-card" key={c.id}><div className="client-card-top"><div className="client-logo">{c.name.split(/\s+/).map(v=>v[0]).join('').slice(0,2).toUpperCase()}</div><Badge tone={c.status==='active'?'green':'slate'}>{c.status==='active'?'Ativo':'Arquivado'}</Badge></div><h3>{c.name}</h3><p>{c.category||'Categoria não informada'}</p><div className="client-stats"><div className="client-stat"><strong>—</strong><span>Campanhas</span></div><div className="client-stat"><strong>—</strong><span>Creators</span></div><div className="client-stat"><strong>—</strong><span>Pendências</span></div></div><div className="client-bottom"><span>{c.instagram||'Instagram não informado'}</span><span>Abrir workspace <ArrowUpRight size={10}/></span></div></Link>)}</div>}
 </>
}
