'use client';

import { useEffect, useMemo, useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';
import { Users, Plus, X, ShieldCheck, Clock3 } from '@/components/icons';
import { Badge } from '@/components/ui';

type TeamUser={id:string;email:string|null;name:string;role:string;created_at:string;last_sign_in_at:string|null};
const roleLabels:Record<string,string>={admin:'Administrador',manager:'Gestor',operator:'Operação',finance:'Financeiro',viewer:'Leitura'};
const roleTone=(r:string)=>r==='admin'?'violet':r==='manager'?'blue':r==='finance'?'amber':r==='operator'?'green':'slate';

export default function Usuarios(){
  const supabase=useMemo(()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;return u&&k?createBrowserClient(u,k):null},[]);
  const [items,setItems]=useState<TeamUser[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [form,setForm]=useState({name:'',email:'',password:'',role:'operator'});
  async function token(){const {data}=await supabase!.auth.getSession();return data.session?.access_token||''}
  async function load(){if(!supabase){setLoading(false);return}setLoading(true);setError('');const t=await token();const res=await fetch('/api/admin/users',{headers:{Authorization:`Bearer ${t}`}});const body=await res.json().catch(()=>({}));if(!res.ok)setError(body.error||'Não foi possível carregar os usuários.');else setItems(body.users||[]);setLoading(false)}
  useEffect(()=>{load()},[supabase]);
  async function createUser(e:React.FormEvent){e.preventDefault();if(!supabase)return;setSaving(true);setError('');setSuccess('');const t=await token();const res=await fetch('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify(form)});const body=await res.json().catch(()=>({}));setSaving(false);if(!res.ok){setError(body.error||'Não foi possível criar o usuário.');return}setSuccess(`${form.name} já pode entrar no Arcana.`);setForm({name:'',email:'',password:'',role:'operator'});setOpen(false);await load()}
  return <>
    <div className="page-head"><div><div className="eyebrow">Configurações · equipe</div><h1 className="page-title">Usuários e acessos</h1><p className="page-subtitle">Contas internas autenticadas pelo Supabase. A senha nunca é salva no código ou exibida depois da criação.</p></div><button className="primary-btn keep-text" onClick={()=>setOpen(v=>!v)}>{open?<X size={16}/>:<Plus size={16}/>} {open?'Fechar':'Novo usuário'}</button></div>
    <div className="grid-metrics"><div className="metric-card"><div className="metric-top"><span>Usuários</span><Users size={15}/></div><div className="metric-value">{items.length}</div><div className="metric-meta">contas vinculadas ao workspace</div></div><div className="metric-card"><div className="metric-top"><span>Administradores</span><ShieldCheck size={15}/></div><div className="metric-value">{items.filter(i=>i.role==='admin').length}</div><div className="metric-meta">acesso total</div></div><div className="metric-card"><div className="metric-top"><span>Operação</span><Users size={15}/></div><div className="metric-value">{items.filter(i=>['operator','manager'].includes(i.role)).length}</div><div className="metric-meta">equipe operacional</div></div><div className="metric-card metric-card-accent"><div className="metric-top"><span>Últimos acessos</span><Clock3 size={15}/></div><div className="metric-value">{items.filter(i=>i.last_sign_in_at).length}</div><div className="metric-meta">usuários que já entraram</div></div></div>
    {open&&<form className="form-card" onSubmit={createUser} style={{marginBottom:16}}><div className="form-section" style={{marginBottom:0,paddingBottom:0,borderBottom:0}}><h3>Criar acesso</h3><p>O usuário será criado no Supabase Auth, confirmado e vinculado ao workspace atual.</p><div className="form-grid"><div className="field"><label>Nome *</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>E-mail *</label><input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="field"><label>Senha temporária *</label><input type="password" minLength={8} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div><div className="field"><label>Perfil</label><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="operator">Operação</option><option value="manager">Gestor</option><option value="finance">Financeiro</option><option value="viewer">Somente leitura</option><option value="admin">Administrador</option></select></div></div><div className="submit-row"><span className="privacy-note">Somente administradores e gestores podem criar usuários.</span><button className="primary-btn keep-text" disabled={saving}>{saving?'Criando…':'Criar acesso'}</button></div></div></form>}
    {error&&<div className="success-box" style={{background:'#fff0f2',color:'#ba3b4d',marginBottom:14}}>{error}</div>}{success&&<div className="success-box" style={{marginBottom:14}}>{success}</div>}
    <div className="panel table-wrap"><table className="data-table"><thead><tr><th>Usuário</th><th>Perfil</th><th>Criado em</th><th>Último acesso</th></tr></thead><tbody>{loading?<tr><td colSpan={4}>Carregando equipe…</td></tr>:items.length===0?<tr><td colSpan={4}>Nenhum usuário encontrado ou você não possui permissão para listar a equipe.</td></tr>:items.map(u=><tr key={u.id}><td><div className="person"><div className="mini-avatar">{u.name.split(/\s+/).map(v=>v[0]).join('').slice(0,2).toUpperCase()}</div><div className="name-cell"><strong>{u.name}</strong><span>{u.email}</span></div></div></td><td><Badge tone={roleTone(u.role) as any}>{roleLabels[u.role]||u.role}</Badge></td><td>{new Date(u.created_at).toLocaleDateString('pt-BR')}</td><td>{u.last_sign_in_at?new Date(u.last_sign_in_at).toLocaleString('pt-BR'):'Nunca'}</td></tr>)}</tbody></table></div>
  </>;
}
