'use client';

import { useEffect, useMemo, useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';
import { CircleDollarSign, Plus, X, Search, ExternalLink } from '@/components/icons';
import { Badge } from '@/components/ui';

type Payment={id:string;amount:number|null;status:string;invoice_url:string|null;due_at:string|null;paid_at:string|null;proof_url:string|null;created_at:string;campaigns?:{name:string;clients?:{name:string}|null}|null;influencers?:{full_name:string}|null};
type Campaign={id:string;name:string;clients?:{name:string}|null};type Participant={campaign_id:string;influencer_id:string;influencers?:{full_name:string}|null};
const labels:Record<string,string>={awaiting_invoice:'Aguardando NF',invoice_received:'NF recebida',scheduled:'Programado',paid:'Pago',cancelled:'Cancelado'};
const tone=(s:string)=>s==='paid'?'green':s==='scheduled'?'blue':s==='invoice_received'?'violet':s==='cancelled'?'red':'amber';

export default function Financeiro(){
  const supabase=useMemo(()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;return u&&k?createBrowserClient(u,k):null},[]);
  const [items,setItems]=useState<Payment[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [participants,setParticipants]=useState<Participant[]>([]);const [orgId,setOrgId]=useState('');const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [form,setForm]=useState({campaign_id:'',influencer_id:'',amount:'',due_at:'',invoice_url:''});
  async function load(){if(!supabase){setLoading(false);return}setLoading(true);setError('');const {data:m}=await supabase.from('organization_members').select('organization_id').limit(1).maybeSingle();if(!m){setError('Usuário sem workspace.');setLoading(false);return}setOrgId(m.organization_id);const [pQ,cQ,iQ]=await Promise.all([supabase.from('payments').select('id,amount,status,invoice_url,due_at,paid_at,proof_url,created_at,campaigns(name,clients(name)),influencers(full_name)').order('created_at',{ascending:false}),supabase.from('campaigns').select('id,name,clients(name)').order('created_at',{ascending:false}),supabase.from('campaign_influencers').select('campaign_id,influencer_id,influencers(full_name)').neq('casting_stage','rejected')]);if(pQ.error)setError(pQ.error.message);setItems((pQ.data||[]) as unknown as Payment[]);setCampaigns((cQ.data||[]) as unknown as Campaign[]);setParticipants((iQ.data||[]) as unknown as Participant[]);setLoading(false)}
  useEffect(()=>{load()},[supabase]);
  async function createPayment(e:React.FormEvent){e.preventDefault();if(!supabase||!orgId||!form.influencer_id)return;setSaving(true);setError('');const {error:e2}=await supabase.from('payments').insert({organization_id:orgId,campaign_id:form.campaign_id||null,influencer_id:form.influencer_id,amount:form.amount?Number(form.amount):null,status:form.invoice_url?'invoice_received':'awaiting_invoice',invoice_url:form.invoice_url.trim()||null,due_at:form.due_at||null});setSaving(false);if(e2){setError(e2.message);return}setOpen(false);setForm({campaign_id:'',influencer_id:'',amount:'',due_at:'',invoice_url:''});await load()}
  async function changeStatus(id:string,status:string){if(!supabase)return;const patch:Record<string,unknown>={status,updated_at:new Date().toISOString()};if(status==='paid')patch.paid_at=new Date().toISOString();await supabase.from('payments').update(patch).eq('id',id);await load()}
  async function addProof(id:string,current:string|null){if(!supabase)return;const url=window.prompt('Cole a URL do comprovante:',current||'');if(url===null)return;await supabase.from('payments').update({proof_url:url.trim()||null,updated_at:new Date().toISOString()}).eq('id',id);await load()}
  const filtered=items.filter(p=>`${p.influencers?.full_name||''} ${p.campaigns?.name||''} ${p.campaigns?.clients?.name||''}`.toLowerCase().includes(query.toLowerCase()));const available=participants.filter(p=>!form.campaign_id||p.campaign_id===form.campaign_id);const openAmount=items.filter(i=>i.status!=='paid'&&i.status!=='cancelled').reduce((s,i)=>s+Number(i.amount||0),0);const paidAmount=items.filter(i=>i.status==='paid').reduce((s,i)=>s+Number(i.amount||0),0);const fmt=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n);
  return <>
    <div className="page-head"><div><div className="eyebrow">Financeiro operacional</div><h1 className="page-title">Financeiro</h1><p className="page-subtitle">Cachês, notas fiscais, vencimentos e pagamentos ligados a creator e campanha.</p></div><button className="primary-btn keep-text" onClick={()=>setOpen(v=>!v)}>{open?<X size={16}/>:<Plus size={16}/>} {open?'Fechar':'Novo pagamento'}</button></div>
    <div className="grid-metrics"><div className="metric-card"><div className="metric-top"><span>Em aberto</span><CircleDollarSign size={15}/></div><div className="metric-value" style={{fontSize:22}}>{fmt(openAmount)}</div><div className="metric-meta">valores ainda não pagos</div></div><div className="metric-card"><div className="metric-top"><span>Aguardando NF</span><CircleDollarSign size={15}/></div><div className="metric-value">{items.filter(i=>i.status==='awaiting_invoice').length}</div><div className="metric-meta">creators pendentes de nota</div></div><div className="metric-card metric-card-accent"><div className="metric-top"><span>Pago</span><CircleDollarSign size={15}/></div><div className="metric-value" style={{fontSize:22}}>{fmt(paidAmount)}</div><div className="metric-meta">histórico registrado</div></div></div>
    {open&&<form className="form-card" onSubmit={createPayment} style={{marginBottom:16}}><div className="form-section" style={{marginBottom:0,paddingBottom:0,borderBottom:0}}><h3>Novo pagamento</h3><p>Crie a obrigação financeira e acompanhe NF, programação e pagamento.</p><div className="form-grid three"><div className="field"><label>Campanha</label><select value={form.campaign_id} onChange={e=>setForm({...form,campaign_id:e.target.value,influencer_id:''})}><option value="">Sem campanha</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.clients?.name} · {c.name}</option>)}</select></div><div className="field"><label>Creator *</label><select required value={form.influencer_id} onChange={e=>setForm({...form,influencer_id:e.target.value})}><option value="">Selecione</option>{available.map(p=><option key={`${p.campaign_id}-${p.influencer_id}`} value={p.influencer_id}>{p.influencers?.full_name||'Creator'}</option>)}</select></div><div className="field"><label>Valor</label><input type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></div><div className="field"><label>Vencimento</label><input type="date" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/></div><div className="field"><label>URL da NF</label><input value={form.invoice_url} onChange={e=>setForm({...form,invoice_url:e.target.value})} placeholder="https://"/></div></div><div className="submit-row"><span className="privacy-note">Sem URL de NF, começa em “Aguardando NF”.</span><button className="primary-btn keep-text" disabled={saving}>{saving?'Salvando…':'Criar pagamento'}</button></div></div></form>}
    <div className="toolbar"><div className="search-box"><Search size={16}/><input placeholder="Creator, cliente ou campanha..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div>{error&&<div className="success-box" style={{background:'#fff0f2',color:'#ba3b4d',marginBottom:14}}>{error}</div>}
    <div className="panel table-wrap"><table className="data-table"><thead><tr><th>Creator</th><th>Cliente / campanha</th><th>Valor</th><th>Status</th><th>Vencimento</th><th>NF</th><th>Comprovante</th></tr></thead><tbody>{loading?<tr><td colSpan={7}>Carregando financeiro…</td></tr>:filtered.length===0?<tr><td colSpan={7}>Nenhum pagamento registrado.</td></tr>:filtered.map(p=><tr key={p.id}><td><strong>{p.influencers?.full_name||'—'}</strong></td><td><div className="name-cell"><strong>{p.campaigns?.clients?.name||'—'}</strong><span>{p.campaigns?.name||'—'}</span></div></td><td>{p.amount!=null?fmt(Number(p.amount)):'—'}</td><td><select value={p.status} onChange={e=>changeStatus(p.id,e.target.value)} style={{border:'1px solid #e1e3eb',borderRadius:9,padding:'7px 8px',background:'#fff'}}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div style={{marginTop:5}}><Badge tone={tone(p.status) as any}>{labels[p.status]||p.status}</Badge></div></td><td>{p.due_at?new Date(`${p.due_at}T12:00:00`).toLocaleDateString('pt-BR'):'—'}</td><td>{p.invoice_url?<a href={p.invoice_url} target="_blank" rel="noreferrer" className="ghost-btn">Abrir <ExternalLink size={12}/></a>:'—'}</td><td>{p.proof_url?<a href={p.proof_url} target="_blank" rel="noreferrer" className="ghost-btn">Abrir <ExternalLink size={12}/></a>:<button className="ghost-btn" onClick={()=>addProof(p.id,p.proof_url)}>Adicionar</button>}</td></tr>)}</tbody></table></div>
  </>;
}
